### ISSUE TITLE
is there any plan to restore  pkcs#11  support in future version?

### ISSUE THREAD

**Issue by achilles78** [NoMoreFood/putty-cac#1]
The pkcs11 support has been removed from v0.65.
is it possible to support pkcs11 in future version?

**Comment by NoMoreFood** [comment]
I'll have to investigate a little since I'm not sure how intrusive the pkcs11 support was.  If any others need this capability, I'd appreciate them chiming in here.  And, if possible, provide any pkcs11 support binaries / document that might be available.

**Comment by NoMoreFood** [comment]
@achilles78 Any reason why you closed this?  Are you still interested in pkcs11 support?

**Comment by achilles78** [comment]
i'm interested in pkcs11 support.
in my routin work , i want to use token-based authentication for putty ssh login with some common usb tokens such as Aladdin eToken PRO, Fetain epass 2003, Fetain epass 3000 etc.

**Comment by NoMoreFood** [comment]
@achilles78 I'm actively working this and it should be available in a week or two.  I'm reworking the code entirely to have it fit better with the current source code.  Are you be willing to assist in testing prior to release?

**Comment by achilles78** [comment]
Yes, i'm willing to assist in the testing.

**Comment by TobiHH** [comment]
I'm looking forward to it too. I would test it also. I'm using a yubikey with smart card functionality.

**Comment by NoMoreFood** [comment]
@TobiHH @achilles78 See attached. You may have to re-setup any setting with existing PuTTY configs. Let me know how it goes.

[puttycac-0.68u2-prerelease.zip](https://github.com/NoMoreFood/putty-cac/files/919337/puttycac-0.68u2-prerelease.zip)

**Comment by achilles78** [comment]
@NoMoreFood 
well done.
i have tested  pub key login by using  pkcs11 certificate stored in usb token and it works well.
the test enviroment is VMWare workstaion 12.5.5 + Windows 7 professional 64bit 
i tested three kinds of usb tokens:  Feitian ePass2003 , Feitian ePass3000, and et199( a very cheap usb token 	
manufactured by a Chinese company)

**Comment by NoMoreFood** [comment]
@achilles78 Thanks for the feedback!  I'm planning an official pre-release for next week.  This will incorporate the PKCS changes as well as elliptic curve support for CAPI.  Any additional testing that you can provide then would be greatly appreciated.  

@TobiHH Did you have a chance to test?

**Comment by TobiHH** [comment]
Hello,
I've tried it. But I'm not really sure if i've done right. I've expected something like this. https://risacher.org/putty-cac/ Where I could select "pkcs11". I didnt find anything like that. What do I have to do?

**Comment by NoMoreFood** [comment]
@TobiHH  Thanks for the feedback.  It sounds like you really didn't need direct PKCS #11 library support if the 'Set CAPI Cert...' button work.  Regardless, I'm happy that it's working for you.

And yes, if you're looking for the PIN to be remembered, then use Pageant.

**Comment by TobiHH** [comment]
The Pageant remembers the pin on one machine. On the other it doesn't remember the pin. I'm not sure whats the difference. I've to find out. 

If I choose a "CAPI Cert" my discission is lost the next time i start the pageant. Is there a possibility to store the selected CAPI cert?

**Comment by NoMoreFood** [comment]
@TobiHH In terms of storing the CAPI certificate, you have two options.  You can pass a command line argument to Pageant that specifies the certificate to load or you can try the 'Autoload Certs' options in the Pageant menu.

**Comment by NoMoreFood** [comment]
These changes have made their way into PuTTY CAC 0.68 Update 2 Pre-Release.  Closing this out.  If you have any problems with the pre-release, please create a new issue.
