### ISSUE TITLE
Putty-CAC 0.70u1 issue with Windows 7

### ISSUE THREAD

**Issue by wmagb** [NoMoreFood/putty-cac#10]
We are running the 64-bit version of Windows 7 Enterprise w/SP1 installed, and when we update to 0.70u1, we are then unable to launch the PuTTY software, getting an error dialog box "Failed to initialize COM subsystem".
![putty-cac_error](https://user-images.githubusercontent.com/30704117/28942313-e75e4c58-7868-11e7-8eff-65e629b4b4d1.jpg)

I should note, this is using the 32-bit version of putty-cac, and we have ActivClient 7.1.x installed.

We were using 0.70 with no issues, as well as the previous versions, 0.68 and 0.68u1, all 32-bit.

Thanks.

**Comment by NoMoreFood** [comment]
I'm really starting to hate this hijacking protection code in the upstream.  Does it occur with 64-bit PuTTY CAC?  Does it occur when ActivClient is uninstalled?

Are you willing to run a few tests to see how to best work through the issue?  I suspect we may need to just move the COM initialization before calling SetDllDirectory().

**Comment by NoMoreFood** [comment]
Disregard previous questions.  I can reproduce it.  Investigating...

**Comment by NoMoreFood** [comment]
Please try the pre-release I posted.

**Comment by wmagb** [comment]
Looks like it is working! Thank you very much.
