### ISSUE TITLE
Importing OpenSSH ecdsa-sk key crashes Puttygen

### ISSUE THREAD

**Issue by ajf8** [NoMoreFood/putty-cac#100]
Hi,

Thanks so much for supporting FIDO tokens (I'm using one called a trustkey), it's really excellent. Would it be possible to support importing existing OpenSSH ecdsa-sk keys into putty-cac?

I attempted this to import it as an OpenSSH key in Puttygen but it just crashed. Apologies, I can't get a crash report out of the particular network I was testing on and don't have a Windows machine at home, but I think it should be easily reproducible.

It was a resident ecdsa-sk key (I would have tested ed25519-sk but my key doesn't support it) generated using the following command:
```
ssh-keygen -t ecdsa-sk -O resident -O application=ssh:myuser
```

Using PuTTY CAC 0.77 Update 1, running puttygen.exe from the zip release.

Thanks!

**Comment by NoMoreFood** [comment]
@ajf8 PuTTY CAC really don't have any special features/capability within PuTTYgen.  For ease of maintanance, most of the creation/import capabilities are housed in the normal PuTTY application. Have you tried the 'Import Keys' there?  You shouldn't even need the original file for resident keys; it will read them from the token directly.

![image](https://user-images.githubusercontent.com/12881023/186779647-d168f0fe-63a2-4648-a1db-272b7df83393.png)

**Comment by ajf8** [comment]
Thanks. I have, unfortunately the issuer of the key didn't and won't provide the PIN. It was given to me with a SSH key associated with my identity and I was provided the OpenSSH key files.

It works great when I create a new key, but I was hoping to use my existing key file in OpenSSH format. Perhaps this makes no sense at all and I should have the PIN.

**Comment by NoMoreFood** [comment]
@ajf8 Yeah, that is a bit unusual of an usual scenario.  I will ponder how we might be able to satisfy your use case.

**Comment by ajf8** [comment]
FWIW after having a read of puttyimp.c and OpenSSH's PROTOCOL.u2f docs I found a hacky way to import the key - read the private key using a python module called openssh-key-parser to extract the key_handle (credential id) and public key bytes (just the q/ec_point without OpenSSH specific headers), then convert them into hex and generate a .reg file (using a .reg export of my working key generated by putty-cac as a reference):

```
import openssh_key.private_key_list as pkl
sk = pkl.PrivateKeyList.from_string(open(sys.argv[1]).read())[0]
credid = to_hexcsv(sk.private.params['key_handle'])
pubkey = "45,43,53,31,20,00,00,00," + to_hexcsv(sk.public.params['q'])[3:]
```

**Comment by NoMoreFood** [comment]
@ajf8 Impressive reverse engineering; wish all the people that submitted issues were as savvy ;-) I will likely add some similar functionality to PuTTY CAC interface in the next coming weeks so let's leave this issue open to track it.

**Comment by ajf8** [comment]
it was a fun little problem to solve and I learned some useful things about FIDO authentication :) 

Thank you for considering the feature request even if it seems like a weird scenario to not have the PIN, whenever you feel like having a go I can try to test it. I'm not sure as I'm no expert in this field, but having SSH key set on a user token at the time it is issued to them and not giving them the PIN to admin the key seems like a good idea (for some not all organisations). Conversion with OpenSSH key interoperability  is a great feature of PuTTy which would be good to continue with security key types.

You can verify their identity at this stage, and at the same time record their public key for your services. Linux sssd+sshd supports reading OpenSSH format public keys from LDAP. My idea is that anyone can have a SSH key pre-created by their organisation when the FIDO device is enrolled with their fingerprint, then the public key goes into LDAP so they can login to hosts that support FIDO keys. Maybe the Windows host they connect from can already have the key configuration imported using something like the method above to generate a .reg file.

One thought I had is can we use existing webauthn identities? If there's a compatible the key is stored with do we really need to make separate identities for each?

**Comment by NoMoreFood** [comment]
@ajf8 Can you try the most recent binaries here: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

I added an 'Import Key File...' button within PuTTY's FIDO tools.

> My idea is that anyone can have a SSH key pre-created by their organisation when the FIDO device is enrolled with their fingerprint, then the public key goes into LDAP so they can login to hosts that support FIDO keys.

Yes, I imagine that could be done.  This concept very similar to how several organizations are doing multi-factor authentication, but instead using the public key associated with certificate keypairs that are delivered with their smartcards.  There's code within https://github.com/NoMoreFood/putty-cac/blob/master/tools/CertificateTransformer.ps1 that can be used to generate data that can be used in a centralized AuthorizedKeys file managed by the OpenSSH configuration file.

> One thought I had is can we use existing webauthn identities? If there's a compatible the key is stored with do we really need to make separate identities for each?

If those identities use resident keys (or can have their information extracted using another mechanism), then I don't see why not.  However, the current PuTTY CAC code will only import keys that have an 'ssh:' prefix just to avoid importing loads of extra stuff.

**Comment by ajf8** [comment]
Wow thanks @NoMoreFood . I'm just waiting on getting the updated binaries in the place needed and then I will give it a try, or I may setup a Windows VM at home. Looks great, I was wondering what that byte at the start of the public key I had to throw away was for, the compression type.

**Comment by NoMoreFood** [comment]
@ajf8 Any luck testing this?

**Comment by ajf8** [comment]
Hi @NoMoreFood sorry for the delay on testing, it did me take a while to get hold of the updated binaries internally and then was busy, but I tested it properly today and it works great! Thank you for taking the time to implement it.

**Comment by NoMoreFood** [comment]
Okay, going to close this issue.  Release will be in the next week or two.  Thanks!
