### ISSUE TITLE
Win10 plus Pageant using fido key fails 

### ISSUE THREAD

**Issue by dkalog** [NoMoreFood/putty-cac#102]
Hi ,
Many Kudos  for Putty CAC, 

I am using a yubikey nfc5 .  My key hosts, among others, a  FIDO key. I have managed to  ssh to a remote server using the latest microsoft openssh client and a debian opensshd server in (password-less) key based authentication. (So I have a working "pair"). However when I try to use the fido CAPI, it fails. (As I have multiple keys on the server, I have verified that pageant works with ordinary keys.) My pageant key list is loaded with my multiple keys one of them being the fido key. 

the plain behavior when my authorized_keys have a single entry  of... sk-ecdsa-sha2-nistp256@openssh.com it asks for a pssword. It seems as if the pageant serves no key on the remote side. However when I comment out my regular RSA key key authentication works normally.

When I am attempting using fido tools (key management) import operation I am being asked for a pass but again I am presented with password !!

While verifying the working solution of MS ssh client ( I have noticed that it calls debug1: provider C:\\Program Files\\Yubico\\Yubico PIV Tool\\bin\\libykcs11.dll: ) the corresponding provider.  Although pageant has loaded the FIDO key ...(sk-ecdsa-sha2-nistp256@openssh.com AAAA.....Og==  FIDO:ssh:    putty-cac keeps asking for password based authentication and nvers ask for a touch on the key. I attempted to import the key but the same behavior persists.

Cheers

**Comment by NoMoreFood** [comment]
You've mentioned FIDO, CAPI and implied your using PKCS (by the use of libykcs11.dll).  These are all different ways to communicate with your key.  Can you provide screenshots or the specific commands of what works with the Microsoft SSH client?  Can you also screenshot the list of keys showed in Pageant and what option you used to add it?

**Comment by dkalog** [comment]
Hi Bryan

From a windows terminal

C:\Users\Dimitris\.ssh>ssh-add -L
ssh-rsa
AAAAB3NzaC1yc2EAAAABIwAAAQEAzIaQ0AeVVJ3lbbWGcQkrHc/H4cv0q7/gcwls6pJZSARQkbveFRf6rs9fgEyu40pKVQo/pJyEsecNDx/EFeq9W4XYQoJBsFpwsOFl04Mg9oRYwpEpbYasGpcfatWHQI/d+Zt9pHk5E5vcDx39j7J/QA6sDp8mWJ0/gD4VES20X7bOi+yZkR6B9PqaA3W6qtJ49SCCDE3XZrJSvuV3HsHvQJ3cH+pzf5oC6tKtBQ7NnfCXNEqhEFDsnNFtVB4UakJWprjJqgNephBcHNV9B3OJiKuS6lB2iV4f6InTwtkLeyMMXAUeEJT0X8FqMmryuc6rLsL0p5xkklrBbl8tsXjlpQ==
imported-openssh-key
***@***.***
AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBDLioDzy21eH1XzBdy+Ac1+AzH+KwLMi+UNF7K3vyMcQXFibHKAeTyiXaJZSDK5neKl84yE++n515NNlRpLcuA8AAAAHc3NoOmlkcA==
Host:Foo4 Security Key:yubikeyusb

Following yubico guidelines I have a config file inside my .ssh directory
C:\Users\Dimitris\.ssh>type config
PKCS11Provider "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll"


C:\Users\Dimitris\.ssh>ssh -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3


1st Experiment :

My remote server with only FIDO key in the authorized_keys

[image: image.png]

attempting  ssh ***@***.***

[image: image.png]
asking for the pin

[image: image.png]

before OK

[image: image.png]

after verifying PIN and before asking to touch the key
and then finally letting me in the server

Now with the combination of putty-cac and pageant:

1) Pageant-cac  with keys being loaded

[image: image.png]

and putty has been configured to use pageant for authorization

[image: image.png]

when I press Open

[image: image.png]

it asks for a password

 Someone would assume that I have a wrong authorized_keys or/and
sshd_configuration.. However when I comment in the FIDO SSG key on the
remote side

[image: image.png]

public key authentication works perfectly

[image: image.png]

In the above screen you see the first two lines from the failed attempt and
then when I asked for a restart it logged in without an issue.

Kind regards
Dimitris



Dimitrios K. Kalogeras

Electrical Engineer Ph.D.
Network Engineer
_____________________________________
skype: aweboy
voice: +30-210-772 1863
fax:     +30-210-772 1866
e-mail: ***@***.***

**Comment by NoMoreFood** [comment]
Your screenshots did not render.  Can you try updating/editing your last post using the website?

**Comment by dkalog** [comment]
From a windows terminal

C:\Users\Dimitris\.ssh>ssh-add -L
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzIaQ0AeVVJ3lbbWGcQkrHc/H4cv0q7/gcwls6pJZSARQkbveFRf6rs9fgEyu40pKVQo/pJyEsecNDx/EFeq9W4XYQoJBsFpwsOFl04Mg9oRYwpEpbYasGpcfatWHQI/d+Zt9pHk5E5vcDx39j7J/QA6sDp8mWJ0/gD4VES20X7bOi+yZkR6B9PqaA3W6qtJ49SCCDE3XZrJSvuV3HsHvQJ3cH+pzf5oC6tKtBQ7NnfCXNEqhEFDsnNFtVB4UakJWprjJqgNephBcHNV9B3OJiKuS6lB2iV4f6InTwtkLeyMMXAUeEJT0X8FqMmryuc6rLsL0p5xkklrBbl8tsXjlpQ== imported-openssh-key
[sk-ecdsa-sha2-nistp256@openssh.com](mailto:sk-ecdsa-sha2-nistp256@openssh.com) AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBDLioDzy21eH1XzBdy+Ac1+AzH+KwLMi+UNF7K3vyMcQXFibHKAeTyiXaJZSDK5neKl84yE++n515NNlRpLcuA8AAAAHc3NoOmlkcA== Host:Foo4 Security Key:yubikeyusb

Following yubico guidelines I have a config file inside my .ssh directory config file
C:\Users\Dimitris\.ssh>type config
PKCS11Provider "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll"


C:\Users\Dimitris\.ssh>ssh -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3


1st Experiment :

My remote server with only FIDO key in the authorized_keys



![image1](https://user-images.githubusercontent.com/5719387/193443844-1ab9dd3e-9dec-4d4d-901c-8742b50d6ee5.png)


attempting  ssh  dkalo@62.217.XXX186 

![image2](https://user-images.githubusercontent.com/5719387/193443921-7aa0ada3-12b6-4f25-8b67-04ecc6c99980.png)

asking for the pin

![Image3](https://user-images.githubusercontent.com/5719387/193443955-1c344f32-6f78-4f11-b3f5-71f97dd36993.png)

before OK
 
![Image4](https://user-images.githubusercontent.com/5719387/193443988-87aff56c-3eec-4314-bc14-8e6fea591168.png)


after verifying PIN and before asking to touch the key
and then finally letting me in the server

Now with the combination of putty-cac and pageant:

1) Pageant-cac  with keys being loaded 

![Image5](https://user-images.githubusercontent.com/5719387/193444122-b11e2259-812b-4281-914d-521037ca6900.png)

and putty has been configured to use pageant for authorization

![Image6](https://user-images.githubusercontent.com/5719387/193444172-0281a5eb-fb07-4a1f-946e-f7ac29dffd0e.png)

when I press Open

![Image7](https://user-images.githubusercontent.com/5719387/193444228-3d9cf749-4b46-446b-88d7-b30ac412907d.png)

it asks for a password

 Someone could  assume that I have a wrong authorized_keys or/and sshd_configuration.. However when I comment in the FIDO SSG key on the remote side

 
![Image8](https://user-images.githubusercontent.com/5719387/193444299-e06bea89-707d-4705-84d7-8594b612e720.png)

public key authentication works perfectly 

![Image9](https://user-images.githubusercontent.com/5719387/193444330-25af327c-965f-47bb-8e2b-8e63c07dc72e.png)

In the above screen you see the first two lines from the failed attempt and then when I asked for a restart it logged in without an issue.

**Comment by NoMoreFood** [comment]
Okay, I think the thing that stands out to me is that it's loaded the key as `FIDO:ssh` instead of `FIDO:ssh:idp`.  I will try to reproduce this.  How was the key loaded imported into the PuTTY CAC?  Using the `FIDO Tools` -> `Import Keys...`?

**Comment by dkalog** [comment]
Hi ,

I have managed/(lucky enough) to troubleshoot this. I tried today two different ways of importing the Fido Keys.
a) Import keys from putty ( which asked me to provide the PIN but  ended with the same faulty behavior asking for password 

b) via Pageant-CAC, selecting:  add FIDO key which asks for selecting a FIDO ssh certificate. Pageant-CAC DID not ask for PIN KEY !!  THIS certificate is different though for the one I used via ssh-add !! I do not know the reason for this. When/If I added this to the remote authorized keys file, pressed open in the putty, it asked me to touch the usb-key and public key authentication was successful.

**Comment by dkalog** [comment]
Hi again

I have updated with new info regarding the FIDO ssh key.. I can't
understand how putty cac generates this new certificate which is different
from the one via ssh-keygen ..

Kind regards
Dimitris

Dimitrios K. Kalogeras

Electrical Engineer Ph.D.
Network Engineer
_____________________________________
skype: aweboy
voice: +30-210-772 1863
fax:     +30-210-772 1866
e-mail: ***@***.***

**Comment by NoMoreFood** [comment]
For the "sk-ecdsa-sha2-nistp256" authentication method, there is no real certificate when using FIDO, only a public key / private key.  This keypair is actually generated by the card itself (not PuTTY or ssh-keygen).  The certificate that can be displayed in PuTTY / Pageant is just a means to provide information to the user.  

In general, the best way to have keys be importable into PuTTY is to use resident keys:

`ssh-keygen -t ecdsa-sk -O resident -O application=ssh:server`

And then you can import it into PuTTY using the `Import Keys` button under FIDO Tools.
