### ISSUE TITLE
Pageant no longer prompting for PIN - Select smart card device / smart card is ready for use

### ISSUE THREAD

**Issue by jacob-pro** [NoMoreFood/putty-cac#103]
Hi,

Suddenly pageant has stopped prompting me for a PIN, instead giving this window:

![image](https://user-images.githubusercontent.com/16433349/195850779-04677ea2-1932-4120-95f5-ad24653a86ba.png)

I can keep clicking OK a few times and then it gives up - and does not allow me to authenticate.

`Server refused public-key signature despite accepting key!`

Any help would be greatly appreciated

Pageant: 0.77-1
Windows 11: Build 22000

**Comment by jacob-pro** [comment]
After a number of restarts and switching user accounts this seems to have resolved itself - I have no idea what the root cause was though 😕

**Comment by NoMoreFood** [comment]
Once you see that screen it's pretty much in Windows' hands to perform a signing operation so maybe a service was stalled.  Can we close issue this if it's no longer occurring?

**Comment by jacob-pro** [comment]
Sure I will close it 👍 

In case this is useful to anyone else - somebody has told me that updating the YubiKey Minidriver and OpenSC Toolset can fix the issue if it is re-occurring.
