### ISSUE TITLE
pageant.exe no longer honors -certauthprompting switch

### ISSUE THREAD

**Issue by bpfoley45** [NoMoreFood/putty-cac#104]
prior versions of pageant (such as 0.76u4) can be launched with the -certauthprompting switch which enables the pop-up prompt with PIN input. It also appears to set the following reg: 'HKCU:\software\SimonTatham\PuTTY\CertAuthPrompting' to a value of 1

Newer versions, 0.77 and above do not seem to honor this, and in fact the application just fails to start.

Can this be restored?

**Comment by NoMoreFood** [comment]
@bpfoley45 Can you see if these binaries address your issue?

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by NoMoreFood** [comment]
Okay, going to close this issue.  Release will be in the next week or two.  Thanks!
