### ISSUE TITLE
v0.78 + YubiKey + Fido + RDP USB Redirection works a bit... but not completely.

### ISSUE THREAD

**Issue by rbability** [NoMoreFood/putty-cac#106]
This is probably a very niche scenario, so I do not expect this to get solved. But maybe it works for someone and can let me know the tricks to do.

Environment:
- PuTTY CAC 0.78
- Windows 11 Client
- Windows Server 2019 Remote Desktop
- YubiKey 5 NFC
- Generated Resident FIDO Key within PuTTY CAC on my YubiKey

What works:
Starting PuTTY on Windows 11 where the YubiKey is plugged in and using FIDO to open a SSH session. After entering the Username Key exchange happens and Windows prompts me for the PIN. After that I´m in.
![image](https://user-images.githubusercontent.com/59822243/203315391-d1bce0db-326f-4629-a821-514ba11eb41d.png)

What works a little bit:
Connect from Windows 11 (where the YubiKey is plugged in) into a RDS Session host, redirecting the YubiKey with it. Open PuTTY, go to the FIDO Tools and import Keys... that imports the 1 Key that is present on my YubiKey.

What does not work:
Going on from the step before, start the SSH Session to the Server. Enter my Username and Key exchange seems to happen, but there is no prompt for the PIN and so Session creation just stops there.
![image](https://user-images.githubusercontent.com/59822243/203315438-978dbb61-6025-41b9-9882-c7ad6de3428a.png)

What I tried too:
Starting Pageant on the RDS Session host and importing the Key from the YubiKey here... that worked. But when creating the SSH session, it looks like this:
![image](https://user-images.githubusercontent.com/59822243/203315609-dee3a137-af0e-492c-a6e4-06de1786b122.png)

Somehow PuTTY / Pageant seem to be able to access the redirected YubiKey within the Remote Desktop Session, but not completely. As I said before, this is a very special case and I am not even sure if this is something that can be worked on within PuTTY.
If that helps: PIV / SmartCard auth via RDS in that way works. Also if I use the Yubico Test site for Webauthn, that works too within the RDS Session. So access to the Key seems to be possible, but just not in full extend?

**Comment by NoMoreFood** [comment]
It's possible some of the Webauthn APIs we use in PuTTY CAC don't exist in Windows Server 2019. The libraries evolved in Windows 10 over time and Windows Server 2019 is comparable to the first version of Windows 10.  Do you know if Server 2022 behaves any differently?

**Comment by rbability** [comment]
That´s a very good point I did not think about! I should be able to set up a test bed with a Server 2022 RDS Host, but this might take a few days. But I will look into that. Thank you very much :-)

**Comment by rbability** [comment]
Good news! It works with a Windows Server 2022 RDS Host... with a little Surprise, but it works ;-)

To give an overview of the Setup:
- Windows 11 Client, enabled for RemoteFX USB Redirect
- Windows Server 2022 RDS Host, enabled for RemoteFX USB Redirect
- YubiKey 5 NFC plugged into the W11 machine
- RDS Host is a VM

You connect via RDP to the RDS Host while the YubiKey is plugged in and in the RDP Client settings, include the YubiKey, so it get redirected.
On the RDS Host use PuTTY CAC and configure your ssh session. If not done before, use PuTTY CAC Fido Tools to create a resident FIDO Key on your YubiKey.
If you already have a Key and use PuTTY CAC for the first time on the RDS Host, use the Import Key function in the FIDO Tools of PuTTY CAC to import your Key into the Registry.

From this point forward, RemoteFX USB Redirection is not needed anymore! I tried it with USB redirection enabled and disabled, and the following always worked, because the Registry was already populated with the FIDO key information!

Configure your ssh Session to use your FIDO Key and connect.
After connect you enter your Username.
Then LOCAL on your machine where the YubiKey is plugged in, Windows will prompt you for the PIN and the YubiKey will flash to touch it. Do it and you get logged into your ssh session :-)

So @NoMoreFood was right: Windows Server versions prior to 2022 seem to miss the features required for this process. But with a 2022 RDS Host it works. I assume it will also work with a 2022 Server without Remote Desktop Services IF your Registry is populated with the right key, because RemoteFX USB Redirect was not needed to establish the ssh session, just to import / create the FIDO Key. So I assume if you have roaming profiles where the Registry tree of PuTTY migrates with your User account to other systems, it might still work on non RDS enabled RDP connections.
