### ISSUE TITLE
FIDO Keys using pageant

### ISSUE THREAD

**Issue by assid2** [NoMoreFood/putty-cac#110]
I have yubikeys with FIDO resident SSH keys. In linux ssh-keygen -K can access the tokens fine. However, in pageant, when I choose FIDO, it doesnt show up my ed25519-sk key, it just says no certificate available.

I generated the Key using the following: ssh-keygen -t ed25519-sk -O resident -O application=ssh:MyKey -O verify-required

**Comment by assid2** [comment]
In which case, can I suggest in both putty & pageant you create a pane, 
then list it as step 1 import, step 2 discover/ add Fido key. This way 
people know it's a 2 step process, since otherwise it's not intuitive, OR, 
maybe you have both steps being run when someone presses the FIDO button, 
so it imports/ refreshes the registry and then immediately shows what key 
are available.


Regards
Satish

**Comment by NoMoreFood** [comment]
Unfortunately the 'Import Keys...' option requires local administrative privileges which is not always available for users so that's why it's separate. I'll see about adding it into the Pageant GUI though.
