### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rossgrady** [NoMoreFood/putty-cac#111]
Hi folks,

It seems like you've added additional functionality -- which is *awesome* -- to the core PuTTY feature set. 

But I can't find a license file in your repo. Under what license is `putty-cac` distributed?

**Comment by rossgrady** [comment]
Whoops, I found a LICENSE file here: https://github.com/NoMoreFood/putty-cac/blob/master/code/LICENCE

Does that cover 100% of the `putty-cac` distribution, or is it an overlay over the PuTTY license? And does it cover your binaries or just your source?

Since it's not in the root of the repo, GitHub doesn't pick it up, but it also raises the questions I have about what it covers.

Thanks!

**Comment by NoMoreFood** [comment]
PuTTY CAC leverages the PuTTY license which is described at the following link and applies to the binaries and the source code:

https://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html

It is a very permissive license and it wouldn't surprise me if some of the code has made its way into commercial products (which is allowed via the license).

The license text at https://github.com/NoMoreFood/putty-cac/blob/master/code/LICENCE is the same as the one noted on the PuTTY website with some modifications to the contributions and software title.
