### ISSUE TITLE
Request: Test PuTTY CAC 0.79 

### ISSUE THREAD

**Issue by NoMoreFood** [NoMoreFood/putty-cac#114]
All,

Open call for testers.  If anyone is available to test the new version and make sure the PuTTY CAC features work as well as 0.78u1, please post here.  There are no PuTTY CAC specific changes to the code; it's just a merge of the upstream PuTTY code.

**Comment by Jecvay** [comment]
I used 0.79 just now with CAPI Cert and it works fine as before.
old issue: When I unplugged the USBkey, my Peagent automatically exited.

**Comment by NoMoreFood** [comment]
Thanks @Jecvay.  Curious about your old issue... what sort of USB token are you using?

**Comment by Jecvay** [comment]
> what sort of USB token are you using?
very old device, Feitian ePass2001
