### ISSUE TITLE
[feature request] blacklist CN regex on autoload

### ISSUE THREAD

**Issue by frankenstein91** [NoMoreFood/putty-cac#115]
I currently use pageant with @WinSSHTerm and the command line argument -autoload

I have 2 certs that I do not want to load... how to add them to a blacklist?

**Comment by NoMoreFood** [comment]
Open to the idea in principle, but that part of the code is all plain C, and I really don't want to include a third party regex library or use C exports in a standalone C++ library just for that purpose.  Do you think a simple substring match would still be beneficial?

**Comment by frankenstein91** [comment]
substring match is like `*word*`? If yes... yes it would be beneficial and help me a lot

**Comment by NoMoreFood** [comment]
@frankenstein91 Final poke.

**Comment by frankenstein91** [comment]
was able to test today
looks working 

Thank you

**Comment by NoMoreFood** [comment]
Published as pre-release (same binaries).
