### ISSUE TITLE
Request: Add FIDO2 Display Name Textbox

### ISSUE THREAD

**Issue by Aetherinox** [NoMoreFood/putty-cac#117]
Is their any way we can add a new field to the `FIDO Tools` section which allows us to pick our own Display Name for the fido key? Currently, if you import to a Yubikey, the display name is `PuTTY FIDO User` which is coming from `code\cert\cert_fido.c`

```
#define FIDO_KEY_USERNAME L"PuTTY FIDO User"
```

I'm referring to the settings under **Connection** -> **SSH** -> **Certificate** -> **FIDO Tools**

![image](https://github.com/NoMoreFood/putty-cac/assets/118329232/482a8314-38af-4cba-8fd4-81724fa40c4e)

And then just updating `code\cert\cert_fido.c`

```
tUserInfo.pwszDisplayName = FIDO_KEY_USERNAME;
tUserInfo.pwszName = FIDO_KEY_USERNAME;
tUserInfo.cbId = wcslen(FIDO_KEY_USERNAME) * 2;
tUserInfo.pbId = (PBYTE)FIDO_KEY_USERNAME;
```

Seems small, but it would be a damn Christmas gift to get this.

**Comment by NoMoreFood** [comment]
I will take a look this weekend.

**Comment by Aetherinox** [comment]
Thanks. I can develop in numerous languages, but my skills in C are very amateur. 

I went through the code, added the new field, updated the functions and made a demo to show exactly what I was referring to

![image](https://github.com/NoMoreFood/putty-cac/assets/118329232/0d1009fe-897b-44d5-b53c-e6359ca4ab29)

The code works great on build, but the only action I've messed with is `code\cert\cert_fido.c` -> `fido_create_key`

```c
BOOL fido_create_key(LPCSTR szAlgName, LPCSTR szApplication, LPCTSTR szAppDisplay, BOOL bResidentKey, BOOL bUserVerification)
{
    WCHAR szAppDisplayUnicode[FIDO_MAX_DISPLAY_LEN];

    if (MultiByteToWideChar(CP_UTF8, 0, szAppDisplay, -1, szAppDisplayUnicode, _countof(szAppDisplayUnicode)) == 0) return FALSE;

    WEBAUTHN_USER_ENTITY_INFORMATION tUserInfo = { WEBAUTHN_USER_ENTITY_INFORMATION_CURRENT_VERSION };
    tUserInfo.pwszDisplayName = szAppDisplayUnicode;
    tUserInfo.pwszName = szAppDisplayUnicode;
    tUserInfo.cbId = lstrlen(szAppDisplay) * 2;
    tUserInfo.pbId = (PBYTE)szAppDisplay;
    tUserInfo.pwszIcon = NULL;
}
```

Then `code\config.c`

```c
struct fido_data {
	dlgcontrol* fido_create_key_button, * fido_delete_key_button, * fido_import_key_button, * fido_import_ssh_button,
        * fido_clear_key_button, * fido_algo_combobox, * fido_app_text, * fido_display_text, * fido_verification_radio, * fido_resident_radio;
};

char* szAppDisplay = dlg_editbox_get(fidod->fido_display_text, dlg);

if (fido_create_key(szAlgId, szAppId, szAppDisplay, bResidentKey, bVerificationRequired))

```
((Still needs a condition to check for empty string))


And `code\cert\cert_common.h`

```c
EXTERN BOOL fido_create_key(LPCSTR szAlgName, LPCSTR szApplication, LPCTSTR szAppDisplay, BOOL bResidentKey, BOOL bUserVerification);
```

---

Sure you can come up with it as well in probably a better fashion. But this just gives a little detail to the request.

Thanks

**Comment by Aetherinox** [comment]
I threw the changes here for now just to track them (if you need or want them)
- https://github.com/Aetherinox/putty-cac/commit/856fbec37d4bb69cca7ec8b927169bfafc3920b7

**Comment by Aetherinox** [comment]
You're welcome. Appreciate the work. This works great, and I've got 8 Yubikeys I have to create FIDO resident keys for, so this just made my life a hell of a lot easier. I can finally finish my FIDO ssh keys.

Thanks again. Super appreciated.

**Comment by NoMoreFood** [comment]
Published as pre-release (same binaries).

**Comment by Aetherinox** [comment]
Thanks a bunch. This makes life just a bit easier.
