### ISSUE TITLE
Feature Request: Option to disable Pin Caching for user

### ISSUE THREAD

**Issue by PalmEmanuel** [NoMoreFood/putty-cac#121]
## Feature Request

In a corporate environment we have the need to disallow the feature "Force PIN Caching" for users who utilize PuTTY CAC. We would like the ability to block users from being able to use the feature completely because of security reasons, as a system-wide setting for machines that install PuTTY CAC.

Feature we would like to hide / disable:

![image](https://github.com/NoMoreFood/putty-cac/assets/3384251/daeef381-6685-41cc-8f4b-949c50fb0a17)

### Suggested Implementation

PuTTY CAC could look for a specific registry key in the machine hive (to ensure non-admin users cannot change it), for example HKEY:/LocalMachine/Software/SimonTatham/PuTTY DisablePinCaching DWORD 1.

This would effectively make PuTTY CAC ignore the following registry value in the user registry hive and treat it as being 0:

![image](https://github.com/NoMoreFood/putty-cac/assets/3384251/1c52e498-8c98-4a59-ba39-9d75e75597d6)

If it's more convenient for you, we would be happy to submit a PR for it.

**Comment by NoMoreFood** [comment]
@PalmEmanuel Could you try this build and let me know if you it works well for you?  It should allow you to override any of those values using the same-named version under HKLM (with whatever value you wanted it forced to).

[puttycac-0.80-enforced-test.zip](https://github.com/NoMoreFood/putty-cac/files/14079616/puttycac-0.80-enforced-test.zip)

**Comment by PalmEmanuel** [comment]
It works well, thank you so much for such a quick implementation! 🙏🌟

**Comment by PalmEmanuel** [comment]
Understood, thanks again! 👍

**Comment by NoMoreFood** [comment]
@PalmEmanuel Can you re-test this change in this prerelease?

https://github.com/NoMoreFood/putty-cac/releases/tag/0.81

**Comment by PalmEmanuel** [comment]
I'll try it out and get back to you, thanks!

**Comment by PalmEmanuel** [comment]
Yep it works, thanks again! Looking forward to the release.
