### ISSUE TITLE
pageant PKI Pin Authentication Window does not show in taskbar

### ISSUE THREAD

**Issue by peted2** [NoMoreFood/putty-cac#123]
Not sure if it is an issue related to pageant or if it is related to my windows machine.

If i connect to a server that requires my CAPI Key, and pageant is aware of it, the window requesting the user to input the PIN for it is not visible in the windows task bar.

Normally i guess it is not too much of an issue, but for my Card it takes sometimes up to 15 seconds to show up.
If i focus on another Program/Window, the only way to access the PIN Request window of pageant is to use [ALT]+[TAB] to find the Program and enter PIN.

**Comment by NoMoreFood** [comment]
This is probably due to the fact that the Pageant windows is a tray application.  I'll see if I can dynamically modify the window style  and set it temporarily due to a taskbar application so you'll be able to select the window easier.

**Comment by NoMoreFood** [comment]
@peted2 I spoke too soon.  When I do something to force entice the PIN prompt in Pageant, it still displays in the taskbar:

![image](https://github.com/NoMoreFood/putty-cac/assets/12881023/9862a2f9-9cc2-4c1c-af6a-ee24e4b3a279)

This on Windows 11.  Do you not see this?  Any environment specifics you can provide?

**Comment by peted2** [comment]
Hello,

thanks first of all for looking into this matter.
I am currently off-shift but for now i am using a Win10 OS. I get no prompt at all for any pageant application. Not even in task bar.
I am currently off-shift but if you could specify what else you are interested in, i will gladly try to get this information.

**Comment by NoMoreFood** [comment]
Maybe a screenshot of the System Information page and more information about the token you are using. I also tried under Windows 10 with my token and was unable to reproduce the issue.

**Comment by peted2** [comment]
Hello,

Regarding the Token: it is a company-issued PKI Card with CAPI Cert on it.
This is the only Cert that gets recognized by pageant.
i hope this is what you were looking for:
![screenshot_pageant - Copy](https://github.com/NoMoreFood/putty-cac/assets/18658679/449d623d-ee31-47e9-a8b5-4144c67b560c)
![sysinfo - Copy](https://github.com/NoMoreFood/putty-cac/assets/18658679/ff2cb413-5120-478e-99c1-5b5280b31da2)

**Comment by peted2** [comment]
Hello,

Device Manager:
![devicemanager - Copy](https://github.com/NoMoreFood/putty-cac/assets/18658679/26198f35-6d02-443f-813d-9633e2550c26)



yes ideed. 'Force PIN Caching' is enabled.
Once i remove this option, for the first connection i get the windows-internal PIN request prompt and pageant appears in the taskbar.

**Comment by NoMoreFood** [comment]
Can see you if the attached helps with PIN Caching is on?  I tried setting the parent for that dialog to the desktop window:

[puttycac-0.80u1.zip](https://github.com/NoMoreFood/putty-cac/files/14550159/puttycac-0.80u1.zip)
[puttycac-64bit-0.80u1.zip](https://github.com/NoMoreFood/putty-cac/files/14550160/puttycac-64bit-0.80u1.zip)

**Comment by NoMoreFood** [comment]
@peted2 Did you have a change to test?

**Comment by NoMoreFood** [comment]
Decided to commit this change with this release:

https://github.com/NoMoreFood/putty-cac/releases/tag/0.81
