### ISSUE TITLE
Possible to get a digitally signed release?

### ISSUE THREAD

**Issue by Hraefin** [NoMoreFood/putty-cac#125]
Gov policy is blocking putty cac due to not being digitally signed.
Awesome work on this!

**Comment by NoMoreFood** [comment]
@Hraefin I've been digitally signing PuTTY CAC for manual years.  Please let me know if there's an executable or installer you're not seeing has the 'Digital Certificates' tab.

<img width="296" alt="image" src="https://github.com/NoMoreFood/putty-cac/assets/12881023/dd27657b-2d50-497d-8c0b-dab26d6a3e98">

Side note: If you're downloading PuTTY CAC (or any application files from the internet), you may need to right-click on the file, go to properties, and uncheck the box noted below. Possible that is your issue.

<img width="297" alt="image" src="https://github.com/NoMoreFood/putty-cac/assets/12881023/e651bdf7-e9f6-4003-809a-54b5a9c33a89">

**Comment by NoMoreFood** [comment]
@Hraefin Did that do it for you?  Please close this out if so.

**Comment by Hraefin** [comment]
Weirdly they didn't show as blocked. The icons didn't render normally either. Downloading the entire zip for the project contained the ones that were proper. 

Thank you! Working beautifully, so much appreciated the work you put into this!
