### ISSUE TITLE
PuTTY-CAC implementation with Cisco Devices and/or ISE. 

### ISSUE THREAD

**Issue by Jacobg693** [NoMoreFood/putty-cac#128]
Great Morning Dev Team,

Is there an implementation plan/guide on PuTTY-CAC integration with Cisco Devices and/or ISE? Need to be able to use PKI to log into the device as a MFA solution. I'm having a very difficult time finding resources. My company chose this solution over Pragmasys. Thanks in advance for any and all support. 

Jacob

**Comment by NoMoreFood** [comment]
There is no way currently.  I believe those use "real" x509v3-ssh-rsa certificated based authentication instead of OpenSSH keypairs.  I really don't have any of that gear to test/develop against so it has not been a priority.

**Comment by Jacobg693** [comment]
Thank you Sir.
