### ISSUE TITLE
plink CAPI authentication issue

### ISSUE THREAD

**Issue by pbartfai** [NoMoreFood/putty-cac#132]
CAPI authentication does not work with plink. tested the following command and not authenticated:
plink user@server -i CAPI:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

putty with same arguments works well.

**Comment by NoMoreFood** [comment]
I just tried it with the latest version and it worked fine for me.  What behavior are you seeing?   Is it possible you have a copy of normal PuTTY's plink in your path?

**Comment by pbartfai** [comment]
You are right, I used wrong binary.
