### ISSUE TITLE
Pageant does not recover from a smartcard being unplugged and plugged back in

### ISSUE THREAD

**Issue by minfrin** [NoMoreFood/putty-cac#133]
While checking the error behaviour of putty-cap, I've noticed that if a smartcard is removed, and then after some time is reinserted, putty-cac does not notice or recover from the unplug event.

The software using pageant in my case is Mountain Duck, browsing a server over scp+ssh works until the smartcard is removed, then the directories being browsed are treated as empty, and this behaviour continues after the smartcard is reinserted.

What I expected to happen was that on re-insert of the smartcard, I would be asked for the PIN and things continue.

The current behaviour signals to the end user that either the network or the server is down, resulting in wasted troubleshooting.

**Comment by NoMoreFood** [comment]
The smartcard is only used during initial authentication and not for any ongoing communication after that point (it can be removed from the reader).  Is the software creating new, individual SSH sessions for every operation?

**Comment by NoMoreFood** [comment]
Please reopen if you can provide more information.

**Comment by bluikko** [comment]
In all the years of using putty-cac I have never experienced pageant problems unplugging a CAPI smartcard and replugging it. PIN will be asked on re-insertion and all continues to work just fine.
