### ISSUE TITLE
Pageant appears to remember smartcard PINs across reboots

### ISSUE THREAD

**Issue by minfrin** [NoMoreFood/putty-cac#134]
After configuring pageant against a smartcard via CAPI, scp works.

Rebooting the machine, logging in and running pageant, scp works again, without asking the end user for the PIN to unlock the smartcard. This suggests the end user's PIN is being stored somewhere on the machine, compromising the PIN to anyone with access to the machine.

Can this behaviour be confirmed?

**Comment by NoMoreFood** [comment]
If this is occurring, it's _definitely_ not in PuTTY CAC.  It might be a "feature" of the specific smartcard minidriver you are using.
