### ISSUE TITLE
Docs request: basic instructions on how to export a public key

### ISSUE THREAD

**Issue by minfrin** [NoMoreFood/putty-cac#139]
One of the pain points that we encounter over and over is "what is your public key (corresponding to the private key of the certificate on your CAPI smartcard)".

Every time we deal with this, we have to unpick a mess of confusion where someone has generated new private keys, gone on some tangent totally misunderstanding how to gain the public key.

Note: public key. The end goal is to grant this user access to something. "Send us your public key" turns into a nightmare.

What is needed is docs, linked to directly from the readme, including screenshots, of the exact steps to take for an end user to extract their public key so access can be granted to them without endless pain.

The nature of smartcards is that the card is in the possession of the end user, probably in another city or another country, and we do not have anyone to walk them through the process. The end user must do this themselves.

**Comment by NoMoreFood** [comment]
Are the instructions [here](https://www.idmanagement.gov/implement/scl-ssh/) (also linked on our main page), not adequate?

**Comment by NoMoreFood** [comment]
@minfrin Thoughts on my prior response?

**Comment by NoMoreFood** [comment]
Closing due to non-response.
