### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by KamiZavage** [NoMoreFood/putty-cac#14]
After i finally figured out how to run these dsp's, trying to make gives an error that says, that /ZI and /Gy are incopatible. How to fix it?

**Comment by NoMoreFood** [comment]
What version of Visual Studio are you running, which platform (32-bit or 64-bit), which configuration (Debug or Release), and which specific project?

**Comment by KamiZavage** [comment]
Thanks for the quick reply. I just downloaded the latest Visual Studio.
I have now tried it on "release" "x86", guess that solved the issue (as it was on "Debug" by default). Though i'm now getting errors all over the place saying "No such file or directory" for some .h files. (assert.h, stdio.h, stddef.h and wchar.h) Are they missing or do i need to generate them somehow?

**Comment by NoMoreFood** [comment]
Microsoft is constantly revving their SDK versions in VS2017.  All you probably need to do is go into each project's properties, select the 'General' category, and then switch 'Windows SDK Version' to the latest version.

**Comment by KamiZavage** [comment]
That actually got rid of some problems (changed it from 8.1 to 10.0.16299.0), though now it can't find licence.h.
Also i noticed that when choosing Windows SDK 10 it automatically changed the target platform to Windows 10 whereas most users still use Win7. Think that might be a problem (i mean, once I eventually get it to run :D)?

**Comment by NoMoreFood** [comment]
License.h is a PuTTY file that should be in the root directory for the project.  This should be referenced as a additional, relative include directory from the VS2017 project directory (i.e. '..\..\..').  This should already be done in the project properties, but you may want to verify.

You can ignore that reference to Windows 10.  The actual compatibility is set with a preprocessor definition flags: _WIN32_WINNT=_WIN32_WINNT_WIN6;WINVER=_WIN32_WINNT_WIN6.  This makes sure the APIs being referenced are available in Windows Vista or later.  I just checked out the project, switched to '10.0.16299.0', and it built fine for me.  

I'll be going dark for the next 10 hours, but if you still have questions, post them here, and I'll try to provide some advice then.

**Comment by KamiZavage** [comment]
Seemingly wasn't done. I have executed the perl script to obtain my licence.h. As i put the licence.h and version.h files into our windows directory, those "not found" errors didnt come up again.
But: After running a build i obtained 12 errors. All about the fact that _platform_ssh_share_cleanup and _platform_ssh_share have been defined multiple times (e.g. in noshare.obj).
So whats the deal this time? 😄

**Comment by KamiZavage** [comment]
I have now tried to compile files in the VS2017 folder. That worked flawlessly! 😅 Was it that I had to use VS2017 all along?
But where are my output files? 😆

**Comment by NoMoreFood** [comment]
The output files are in the 'binaries' directory that lives at the same level as 'windows'.

Yeah, we changed the user interface so it looks a bit different but with the same functionality.  The options are now under the 'Certificate' area.  This site has a write-up on what to look for:

https://pivkey.zendesk.com/hc/en-us/articles/207698876-PIVKey-and-PuTTY-CAC-for-SSH-on-Windows

**Comment by KamiZavage** [comment]
Awesome, thanks for the big help!
So my only problem now would be to get my Yubikey running on windows. I wish it could be as easy as it is on Linux.

**Comment by bluikko** [comment]
What is the issue with YubiKey? Which ones are you using? Working
flawlessly here (almost, PIN entry has a small usability bug which
exists only in putty-cac).

On 2018-01-11 15:18, KamiZavage wrote:

> Awesome, thanks for the big help!
> So my only problem now would be to get my Yubikey running on windows. I wish it could be as easy as it is on Linux. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/NoMoreFood/putty-cac/issues/14#issuecomment-356859379
[2]

**Comment by KamiZavage** [comment]
The problem I have is not directly linked to Putty-CAC. It's more that I can't quite get my Yubikey to be responsive. Either I dont have a path to a PKCS .dll file that makes my yubikey talk to me, or the Yubikey Smart Card Minidriver does not happen to load a Certificate into my MMC once the Yubikey is inserted.

How did you solve that?

**Comment by bluikko** [comment]
Windows 7 and 10 do not need anything to be installed. The drivers will
be installed, if needed, when the YK is connected the first time. 

Depending on how you create/put the certificate to the YK, you may need
to switch the mode of the YK... 

If your certificate does not appear into your User Certificate store (it
is the User store, not System store), check that you have all required
Windows services running (smart card service(s), maybe Certificate
propagation, ..., I do not remember exactly now and no access to check)
and that the certificate is of correct type and in the correct slot on
the YK. 

I recommend the YK tools like "PIV tool" for troubleshooting if the YK
actually works and contains the right config/certificate. To confirm if
the problem is with YK/driver/Windows/something else.

On 2018-01-11 15:54, KamiZavage wrote:

> The problem I have is not directly linked to Putty-CAC. It's more that I can't quite get my Yubikey to be responsive. Either I dont have a path to a PKCS .dll file that makes my yubikey talk to me, or the Yubikey Smart Card Minidriver does not happen to load a Certificate into my MMC once the Yubikey is inserted. 
> 
> How did you solve that? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/NoMoreFood/putty-cac/issues/14#issuecomment-356867479
[2]

**Comment by KamiZavage** [comment]
I have just reset my YubiKey using the PIV tool. I have installed the YubiKey Mini Driver for Smartcards.
When trying to export a certificate onto my Yubikey it says that the inserted Smartcard (Yubikey 4 Smart Card) is not suited for this operation due to missing drivers.
What am I missing out?

**Comment by bluikko** [comment]
Which YubiKey model is it? 

They do not need any manual driver installation on Windows. Drivers are
installed automatically when the YK is plugged in first time. 

Unless you have some corporate policies preventing the default easy
way...

On 2018-01-11 17:32, KamiZavage wrote:

> I have just reset my YubiKey using the PIV tool. I have installed the YubiKey Mini Driver for Smartcards.
> When trying to export a certificate onto my Yubikey it says that the inserted Smartcard (Yubikey 4 Smart Card) is not suited for this operation due to missing drivers.
> What am I missing out? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/NoMoreFood/putty-cac/issues/14#issuecomment-356893617
[2]

**Comment by KamiZavage** [comment]
I'm using the Yubikey 4 Nano (Ver. 4.3.4).
I have now uninstalled the SmartCard and the Smartcard Reader in the device manager and then unplugged my Yubikey from my machine. What next?

**Comment by KamiZavage** [comment]
Also, I have now uninstalled the Minidriver as well as the PIV tool now, just to make sure.
The yubikey itself has been reset using the PIV tool beforehand.
