### ISSUE TITLE
Assertion failed critical error when saving a private key

### ISSUE THREAD

**Issue by kikaragyozov** [NoMoreFood/putty-cac#140]
![image](https://github.com/user-attachments/assets/b03132c6-13fd-45ae-ab96-dff134ec409a)
This occurs when I attempted to save a private key reference to a key generated in my security device via
```
ssh-keygen -t ed25519-sk -O resident
```

What's going on?

Steps to reproduce:

1. Open PuttyGen
2. Load the private key reference
3. Attempt to save it.
4. Exception thrown.

**Comment by NoMoreFood** [comment]
This is not a supported operation in PuTTY.  The way to import FIDO resident keys into PuTTY CAC is using one of the buttons in bottom-right of the PuTTY CAC dialog pane shown below:

![image](https://github.com/user-attachments/assets/1fa739fa-8ba5-4b28-9375-48386ec5331e)

**Comment by kikaragyozov** [comment]
After some tinkering I stumbled upon that, and I can say that everything is working as expected. Thank you for maintaining this and making such an amazing extension out of PuTTy.
