### ISSUE TITLE
pageant crashes when CAPI cert is removed from windows

### ISSUE THREAD

**Issue by DonEstefan** [NoMoreFood/putty-cac#142]
Steps to reproduce:

1. add CAPI cert to pageant and close the pageant window
2. delete the cert in windows certmgr.msc, while it is still loaded in pageant
3. double-click on the pageant tray icon and see it crash

I don't think its a big deal, but I thought I'd report it anyways.

**Comment by NoMoreFood** [comment]
Thanks for reporting.  Doesn't hurt to handle these errors more gracefully.  I will look into it.

**Comment by NoMoreFood** [comment]
Addressed in https://github.com/NoMoreFood/putty-cac/commit/c9e33477c36445ba1df0c12c71e24332f3b3d8f6

**Comment by NoMoreFood** [comment]
Released
