### ISSUE TITLE
Question - Compatability 

### ISSUE THREAD

**Issue by jdasilva-ecs** [NoMoreFood/putty-cac#143]
Hello, wondering if this is compatible with not only DoD CAC but other PIVs?

**Comment by NoMoreFood** [comment]
Should work with basically any smartcard that windows recognizes.

**Comment by NoMoreFood** [comment]
Do you have any other questions?

**Comment by jdasilva-ecs** [comment]
Gotcha, was trying to get this working with 90Meter and we get the windows credentials box to pop up but gives us the smartcard  cannot perform the requested operation..etc. Just wanted to make sure that it was compatible with the certain environment we're in.

**Comment by NoMoreFood** [comment]
Middleware can definitely add some complications / unknowns if it doesn't interact with the CAPI subsystem exactly how we programmed it.  If 90Meter includes a PKCS library, it may be worthwhile to see how that responds.
