### ISSUE TITLE
64bit msi installer uses 32bit installation path

### ISSUE THREAD

**Issue by DonEstefan** [NoMoreFood/putty-cac#144]
I noticed, the installer of the [64bit msi installer for v0.82](https://github.com/NoMoreFood/putty-cac/raw/0.82/binaries/puttycac-0.82-x64.msi) will use "C:\Program Files (x86)\PuTTY\" as the default install location. This path is reserved for 32bit programs.
Due to this mismatch I end up with a second putty-cac installation, instead of an in-place upgrade, when using `winget upgrade NoMoreFood.PuTTY-CAC`.
I would help if the 64bit installer would use "C:\Program Files\PuTTY\" as default install location. I think that is how it used to be (not sure, though).

**Comment by NoMoreFood** [comment]
Yes, I'll get that fixed up. I think I see the problem.

**Comment by NoMoreFood** [comment]
This was fixed with the update.
