### ISSUE TITLE
puttycac-0.82u1-x64.msi detected as malware on VT

### ISSUE THREAD

**Issue by R4inbowD4sh** [NoMoreFood/putty-cac#145]
puttycac-0.82u1-x64.msi (8c01329f1cb0aa39cb8681a323c000dd1517ab70968371100ac5e3d11b3a89f6) is detected as malicious by some vendors on Virus Total : https://www.virustotal.com/gui/file/8c01329f1cb0aa39cb8681a323c000dd1517ab70968371100ac5e3d11b3a89f6/detection

**Comment by NoMoreFood** [comment]
Thanks, I already reported it to Ikarus and they fixed it. Still waiting on Google.

**Comment by NoMoreFood** [comment]
Looks like it's all cleared up now.  Thanks for reporting @R4inbowD4sh
