### ISSUE TITLE
Bug: "The already running Pageant refused to add the key"

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#16]
Hi,

When you like to load a CAPI cerfiticicate using the command-line **and** the Pageant it's already running, then you can't load a new certificate.

Example:

- If you start with _"C:\Program Files\PuTTY\pageant.exe" CAPI:2a361e0c4c53e9f357207b48d9e4762e3a840521_ then the Pageant starts and loads this certificate.

- However, if you first execute _"C:\Program Files\PuTTY\pageant.exe"_ and **after** you run
_"C:\Program Files\PuTTY\pageant.exe" CAPI:2a361e0c4c53e9f357207b48d9e4762e3a840521_ then you see a Window Error with the message **"The already running Pageant refused to add the key"**.

Please, can you improve this behaviour?
The idea is to have the option to load any certificate at any time.
Thank you!

**Comment by NoMoreFood** [comment]
@lars18th, I've coded in a workaround to address this behavior that'll be available later this week.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> I've coded in a workaround to address this behavior that'll be available later this week.

I see the changes in the commits. Thank you! I feel it will work. When the binary be available I'll do a deep test.

**Comment by NoMoreFood** [comment]
@lars18th Binaries have been built.  Please test them.

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by lars18th** [comment]
@NoMoreFood ,

> Please test them.

Tested. Good results! Thank you! :smile: 

However, still one request before close this issue if you agree with it: At time, we need to use the CAPI "fingerprint" from the command line. This is right. However, I suggest to add too the option for use the "name". For example, this works:

_"C:\Program Files\PuTTY\pageant.exe" CAPI:2a361e0c4c53e9f357207b48d9e4762e3a840521_

But this doesn't:

_"C:\Program Files\PuTTY\pageant.exe" CAPI:my-cert_

You agree to implement this?
Regards!

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

In case you have troubles for use "fingerprint" or "name", then perhaps you can change the command line to:

_"C:\Program Files\PuTTY\pageant.exe" CAPI:fp=2a361e0c4c53e9f357207b48d9e4762e3a840521 CAPI:nm=my-cert_

Then the id it's explicit indicated. I hope this helps.
Thank you!

**Comment by NoMoreFood** [comment]
Unfortunately, the proposed naming syntax would uniquely identify a certificate and would be difficult to implement for reasons stated in other threads.

I'm going to close this since the behavior was corrected in commit https://github.com/NoMoreFood/putty-cac/commit/6bdae1c129443822349da3416b24879765cc8252.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Don't worry! Last version it's a great improvement. :smile: 

However, before publishing the next release can you improve the documentation? For example, I don't see how to load PKCS certificates using the command-line. But I discovered it by change:

```
pageant.exe PKCS:001122334455...=C:\Windows\System32\aetpkss1.dll
```

Where the "001122334455..." it's the thumbprint of the certificate. So you can load certs using the command line...

```
pageant.exe <key.file>
pageant.exe CAPI:<thumbprint>
pageant.exe PKCS:<thumbprint>=<pkcs#11lib.dll>
```

I hope you agree!
