### ISSUE TITLE
Question: Full portable mode?

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#17]
Hi,

I downloaded the "Pageant.EXE". And I like to use it in a _PORTABLE_ mode. However, I see that if I check, for example, the option "Autoload Certs" it's saved in the registry.

So I request for a method for using a command-line parameter for disabling the use of the registry. Or an option for disabling the "Autoload Certs". My objetive is starting the Pageant mananger using SCRIPTS, and I don't like to use at all the registry.

Please, can you help me with this?
Thank you!

**Comment by NoMoreFood** [comment]
What are you thoughts on how this request might be satisfied?  A comment line option for it?

**Comment by lars18th** [comment]
> A comment line option for it?

Yes. The idea is add some command-line parameters for overwrite what can be saved in the registry.
You agree?

**Comment by NoMoreFood** [comment]
I have created command line option called '-autoload' that will set the automatically set the AutoloadCerts registry key.  This is probably the most time I can afford to put into this request for the moment.  I'll upload this version later this week.

**Comment by NoMoreFood** [comment]
I added -autoloadoff that will set the registry value to zero in the latest build (https://github.com/NoMoreFood/putty-cac/commit/5f74bce8b0c79035f8b4e1cdd48386b87ec0a036).  That's probably as far as this request is going to go.  PuTTY, in general, uses the registry.  If PuTTY starts providing precedence for portability, this fork will follow suit.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Thank you!

And as you selected to do the simple option of "-force"/"-unforce" parameter, I suggest to also add this other parameter:

- _pinoff_: it overcomes the registry value of the PIN caching, and disables it.
- _pinon_: idem for forcing it.

You agree?

**Comment by NoMoreFood** [comment]
@lars18th Addressed in https://github.com/NoMoreFood/putty-cac/commit/bac4d29bc4a7c691a6780892ca919a9d10b7f637.  Please test.  This will probably be the last change until this goes to pre-release phase.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Tested and working... Thank you!
I feel this can go to pre-relese, even I suggest prior to do the simple interchange described in 
https://github.com/NoMoreFood/putty-cac/issues/19#issuecomment-359379250

Regards!

**Comment by NoMoreFood** [comment]
Since tested working, I'm going to close this issue.  Since I've got to assemble the release notes, I'll put that together soon.

**Comment by lars18th** [comment]
> Since tested working, I'm going to close this issue. Since I've got to assemble the release notes, I'll put that together soon.

OK, and thank you!

**Comment by n00b42** [comment]
I wanted to point to a modified version of putty that allows to store config in files: https://jakub.kotrla.net/putty/

I used it for a long time without issues, and totally forgot that it was a modified version. Until I switched to putty-cac to use my security key and then realized that the local file conf does not work anymore.

Maybe that might be an option?
