### ISSUE TITLE
Suggestion: Certificate name for CAPI certs

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#18]
Hi,

In the "Pageant Key List" at time four different rows are shown:

```
CERT-TYPE  /  KEY LENGTH  /  FINGERPRINT  / COMMENT-NAME
```

For example,

```
ssh-rsa  1024  01:02:03:......  my-cert
ssh-rsa  2048  11:12:13:......  CAPI
ssh-rsa  2048  21:22:23:......  CAPI
```

And as you can see for CAPI certs the name is missing. So, please can you add also the name in this case?

Here can be an example of the suggested format (including the different variants):

```
ssh-rsa  1024  01:02:03:......  KEY(my-cert)
ssh-rsa  2048  11:12:13:......  CAPI(my-card)
ssh-rsa  2048  21:22:23:......  CAPI(my-card2)
ssh-rsa  2048  31:32:33:......  PKCS(dll-name:my-token)
```

I feel this can be easy to implement as the name (Comment) it's stored as a simple STRING and it can contain any info.
You agree?

**Comment by lars18th** [comment]
Hi,

If you prefer, then you can use the same syntax used by the PuTTY-Wincrypt fork, that is:

```
ssh-rsa  2048  11:12:13:......  cert://cn=my-card,thumbprint=abcdef...
```

And you can use "capi://", "key://" and "pcks://" for identifying the protocol. So, the "cn" and "thumbprint" parameters identifies each cert.

The problem, and the reason for this suggestion, it's quite simple: if you use more than one CAPI cert, you can't distinguish between them in the Pageant Key List.

**Comment by NoMoreFood** [comment]
Do you look at these certificates often enough that double-clicking on them is tedious?

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> Do you look at these certificates often enough that double-clicking on them is tedious?

Sure! I have around a dozen of certificates in my card. And I load/unload depending of the circunstances.  I admin a lot of servers. So I need to recognize them in the Window. The main reason? A lot of SSH servers have toubles with a large list of certificates. So, I try to not have more than three or four in memory.

I feel that composing the "Comment" (aka NAME) of the certificate it's mainly a simple STRING composing. So it will be easy to support it. I'm right?

In fact, for PuTTY Keys you're showing the NAME... why not for CAPI & PKCS? :smile:

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Now that I can load certificates using the command line, I can't distinguish them in the List when loaded. Please, try to add the name in the "Comment" field. And if you can, use the same sintax as PuTTY-wincrypt: _"cert://cn=...,thumbprint=..."_. You can review the code if you need it!

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Regarding this request, I see that you use the "userkey->comment" as a method for distinguishing between PuTTY keys, CAPI and PCKS. So, the solution isn't trivial... but not very complex:

- In the file "cert/cert_common.h" you have the generic function "cert_is_certpath(p)". You only need to use one simple method for not add complexity.

- So I suggest to use the _"capi://"_ format for CAPI certificates. And _"pcks://"_ for PKCS. In this case you only need to check the first 7 chars to get the type.

- Also you can use the function proposed in PuTTY_wincrypt "capi_get_description()":

```
 /* 
  * Get rsa key comment on the form "cert://cn=<cn>,thumbprint=<sha1>".
  */
 static PSTR capi_get_description(PCCERT_CONTEXT pCertContext)
 {
 	unsigned int cbCN;
 	PSTR szCN, szSHA1, szResult;
 	unsigned char hash[20];
 	cbCN = CertGetNameStringA(pCertContext, CERT_NAME_ATTR_TYPE, 0, szOID_COMMON_NAME, szCN = snewn(FILENAME_MAX, char), FILENAME_MAX);
 	SHA_Simple(pCertContext->pbCertEncoded, pCertContext->cbCertEncoded, hash);
 	szSHA1 = capi_binary_to_hex(hash, 20);
 	szResult = ((cbCN > 0) && (cbCN < FILENAME_MAX - 64)) ? 
 		dupcat("cert://cn=", szCN, ",thumbprint=", szSHA1, NULL) : 
 		dupcat("cert://thumbprint=", szSHA1, NULL);
 	sfree(szCN);
 	sfree(szSHA1);
 	return szResult;
 }
```

And when loading the cert call to this function, like "rsa->comment = capi_get_description(pCertContext);"

You can get the code (the patch) from: 
https://sourceforge.net/projects/puttywincrypt/files/putty_wincrypt_068_git.patch/download

I hope you will be familiar with other PuTTY forks! :smile: 
Regards!

**Comment by NoMoreFood** [comment]
At this point, I'm not willing to change the format.  It's used internally in too many places, and I have a concern for backwards compatibility that I don't want to account for.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Thank you for the fourth column in the version 0.70u3! This it's sufficient for identify the certificate.
Great job! :smile:
