### ISSUE TITLE
Yubikey piv - capi cert

### ISSUE THREAD

**Issue by muehle28** [NoMoreFood/putty-cac#2]
I'm using Win10 and a Yubikey Neo. If I select "Set CAPI Cert", I can select the SSH Key cert, but there is no input field for the pin showing up. If I connect to the server, I get a popup, that the connection is not possible to establish with this smartcard.
![error](https://cloud.githubusercontent.com/assets/11050646/25268860/91afd1a4-267a-11e7-8a02-0a1e585dc7e1.PNG)

**Comment by NoMoreFood** [comment]
@muehle28   Which release are you using?  Can you post a screenshot of the error message?  Thanks!

**Comment by muehle28** [comment]
I´m using PuTTY CAC 0.68 Update 2 Pre-Release.
![error](https://cloud.githubusercontent.com/assets/11050646/25268973/0db61f2e-267b-11e7-9873-68c80cfbcf27.PNG)

**Comment by NoMoreFood** [comment]
@muehle28 I'm still looking into your issue.  If you wouldn't mind trying the latest binaries (Update 2 Pre-Release #2), I'd appreciate it.  It's possible the problem is related to the anti DLL-injection code that was added to the upstream release, especially if you're using a custom CSP.  Also, if you wouldn't mind sending me or attaching the the registry keys HKLM\SOFTWARE\Microsoft\Cryptography\Calais and HKLM\SOFTWARE\Microsoft\Cryptography\Defaults, that might be helpful.

**Comment by muehle28** [comment]
With version "Update 2 Pre-Release 2" I get the same error. I send you the reg files by mail.

**Comment by NoMoreFood** [comment]
@muehle28 If you could try this version and see if you get the same error, I'd appreciate it:

https://github.com/risacher/putty-cac/files/979008/puttycac-0.69-newlookup.zip

**Comment by NoMoreFood** [comment]
@muehle28 Have you had a chance to test?

**Comment by NoMoreFood** [comment]
Closing this item due to lack of response from the submitter.

**Comment by bluikko** [comment]
FWIW, I just tested the same model smart card on English language Windows 10, using Pageant-CAC and stock PuTTY (not loading cert to PuTTY but to Pageant) and it works without issues.

**Comment by bpillatsch** [comment]
I just resolved this issue on my system. Ended up being the chuid needed to be changed/reset, apparantly if you make changes to the PIV slots without changing the chuid windows will not successfully auth with the Yubikey.

**Comment by NoMoreFood** [comment]
Good to hear.  Thanks for following up!

**Comment by KamiZavage** [comment]
My team also got this error today in version 0.7 update #2
