### ISSUE TITLE
Suggestion: Pageant with Export Public Key certificate's

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#20]
Hi,

I suggest to add a button with the name "Export Public Key" (or add the right button option with this option) for exporting the Public Key of the selected cert.

Other similar projects, when you do a double-click over a cert will copy the Public Key (the text used for paste into the ".authorized" file) to the clipboard. However, as this projects opens the Certificate Display windows when you double-click, then another option will be useful for copy the public key.

You agree?

**Comment by NoMoreFood** [comment]
I presume this is referring to Pageant?

**Comment by lars18th** [comment]
> I presume this is referring to Pageant?

Yes! :smile:

**Comment by bluikko** [comment]
I find this suggestion useful if it would export in SSH key format - because I do not know how exactly to convert/construct the "SSH key format" for a certificate.

Currently using other ways to obtain the public keys for SSH so I have not checked the exact syntax. I wonder if this is documented somewhere? CAPI:// etc.

**Comment by lars18th** [comment]
Hi @bluikko ,

If you need some example, you can take the code from the PuTTY fork "wincrypt"...

Download the patch file from: https://sourceforge.net/projects/puttywincrypt/files/putty_wincrypt_068_git.patch/download
And check the functions "key_to_clipboard2()" and "key_to_clipboard()".

I feel you can found a good example on it. :smile_cat:

**Comment by NoMoreFood** [comment]
I think we already have code to do that formatting, unless I'm mistaken.  Aren't you just talking about the functionality that we have in PuTTY when you click the 'Copy To Clipboard' button in the Certificate area?

**Comment by bluikko** [comment]
So basically all it is is "ssh-rsa " + base64 of the public key, and the CAPI:// part is just a comment, it seems.

**Comment by NoMoreFood** [comment]
@bluikko , @lars18th.  I already have a test version staged in my local git repository that I'll upload later this week.  In terms of the key format, it's a little more complicated then the base64 of the public key and differs for ECC versus RSA, but luckily ssh2_pubkey_openssh_str() from the upstream takes care of the heavy lifting.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> Aren't you just talking about the functionality that we have in PuTTY when you click the 'Copy To Clipboard' button in the Certificate area?

Yes! This will be very usefull with CAPI and PKCS certificates, as probably you don't have the public key in the correct format for copy it in the ".authorized" file.

> I already have a test version staged in my local git repository that I'll upload later this week.

Great! I'm impatient to test it. :smile:

**Comment by bluikko** [comment]
@lars18th 
Please excuse me but may I inquire what kind of card (even just the manufacturer name...) you use when using a ton of certificates?
I suspect something very enterprisey like Gemalto etc?

I'm currently using YubiKeys but it seems their "slot" system is actually a single-slot only on Windows, plus they have some other issues... cheap & easy to get, though, ....

**Comment by lars18th** [comment]
Hi @bluikko ,

> Please excuse me but may I inquire what kind of card (even just the manufacturer name...) you use when using a ton of certificates?

Yeah! Gemalto and SafeSign, plus some others. I use more than one card at time (multiple readers). I get them from educational institutions. These cards can store more than one token. I prefer smartcards than YubiKeys as they are inexpensive. However, I suggest to have a secure copy of the tokens as the smartcards are prone to fail after a lot of use.

Regards.

**Comment by bluikko** [comment]
@lars18th 
Separate readers are a non-starter here, it would need to be in USB form factor.

But thank you. It seems quite difficult in general to find opinions and operational experiences about smart cards so I am always asking what others are using.

</thread hijack>

**Comment by NoMoreFood** [comment]
@lars18th Binaries have been built.  Please test them.

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by bluikko** [comment]
Seems to work nicely on my first test with CAPI cert. I tried clicking around and did not notice anything special.

Not sure if having Ctrl-C as shortcut instead of a new button control would have been easier...

Would "C&opy to Clipboard" work for the keyboard, by the way?

**Comment by bluikko** [comment]
One note: keyboard navigation. Personally I rarely use it.

Tab does not work - it works in vanilla Pageant. If the list has focus, alt-shortcuts do not work.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

It works, thank you! :smile: 

Only one simple suggestion before the final release: Change the name of the button to "Copy public key to the Clipboard". This will be more easy to understand.

**Comment by NoMoreFood** [comment]
I added Ctrl-C as well in latest build.

**Comment by NoMoreFood** [comment]
@bluikko I added shortcut keys for the extra buttons in PuTTY-CAC / Pageant.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Done! Thank you!
I suggest then to close this issue; even you consider my last request at #19.

Regards!

**Comment by bluikko** [comment]
Great feature so thanks for all your hard work.
I know how sometimes a simple feature turns into an endless stream of requests, but here it goes anyways:

I have a suggestion that to me looks simple and useful but someone else might disagree. Looking for opinions. If there is only one loaded key, could the "Copy To Clipboard" button work always and copy the single key, even if that key is not selected in the list?

Right now the button does nothing if no key is selected in the list, even if there is only a single key loaded.
