### ISSUE TITLE
Suggestion: Pageant "-run" command line

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#23]
Hi @NoMoreFood ,

In my daily use I open a lot of times: PuTTY, Pageant and KeePass (with the KeeAgent plugin). So, I need to load the Pageant every time I start the PuTTY. Why? Because I don't like that other Pageants act as _server_ (yes, I use them in a _client_ mode). The problem is that: the first Pageant needs to be the _server_. So, if I like to use the Pageant-CAC I have two options:

1. Automatically load it at logon (it consumes memory).
2. Load it when I open the PuTTY.

So, my suggestion it's add a command-line "-run" to the pageant for running another binary when the Pageant it's loaded. In my case, this will be the PuTTY executable. So, starting a direct access to Pageant I can really open a new PuTTY session. This will grant that the Pageant it's loaded when I open the PuTTY for the first time.

Futhermore, the use of this parameter should imply that the window "Pageant is already running" will not be shown. As the Pageant will be called multiples times (or you can add too the command parameter "-nocheckrunning" if you prefer it).

You agree with this enhancement?
Thank you!

**Comment by NoMoreFood** [comment]
I'd recommend proposing this idea to the upstream PuTTY package.  I don't see anything that would necessitate this being associated with PuTTY CAC.

**Comment by lars18th** [comment]
>  I don't see anything that would necessitate this being associated with PuTTY CAC.

For example, running some PKCS software based on a emulator.

Are so complex to implement it? :smile: 

> I'd recommend proposing this idea to the upstream PuTTY package.

I'll be very happy if this and other PuTTY-CAC functions will be incorporated to the PuTTY mainstream. However, it's quite difficult to achieve it.

**Comment by NoMoreFood** [comment]
No plans to implement this.  This request is too niche and can be easily accomplished using an outside script.
