### ISSUE TITLE
Suggestion: Pageant PKCS#11 libraries shortcut

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#24]
Hi,

Some times I use (or I test) the PKCS#11 API. However, It's a pain to search each time for the DLL library.

Why not include a list of used libraries? This will provide a more user friendly interface.

You agree? :smile:

**Comment by NoMoreFood** [comment]
Does the file selection dialog most recently used list not show your most recently used libraries?

**Comment by lars18th** [comment]
> Does the file selection dialog most recently used list not show your most recently used libraries?

No. It only shows the _last_ path... that it's typically `C:\windows\system32\`. And here are a lot of files!

My suyggestion it's save a list of the _files_ (not the directory). Like this:

```
safesign="C:\windows\system32\aetpkss1.dll"
gemalto="C:\Program Files (x86)\Gemalto\Classic Client\BIN\gclib.dll"
opensc="C:\windows\system32\opensc-pkcs11.dll"
```

You can save these values manually. And the PuTTY-CAC only needs to add a list for loading the lib that the user likes.
More or less it's similar to the Mozilla Firefox PCKS#11 manager.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Please, can you consider to add this "used DLL shortcut" function?

Thank you!

**Comment by NoMoreFood** [comment]
@lars18th This would require the creation of a custom dialog which is quite tedious within PuTTY, which uses no modern UI framework.  I have, however, updated the default PKCS DLL filter in the latest pre-release to more easily select *pkcs*.dll files.  Please check it out.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

I tested the new release... And I have a _simple_ idea that perhaps you like to implement... Se this image:

![putty-cac](https://user-images.githubusercontent.com/9989964/38239376-cc183a3e-372c-11e8-95b5-cd666d5440d9.png)

You can add a simple "sub-menu" entry in "PCKS Certs" with a list of "predefined DLL libraries". With this sub-menu you can directly load the DLL without any Open Window. Futhermore, in the CONFIGURATION you can store the path of the predefined libraries (without any UI helper), like:

```
safesign="C:\windows\system32\aetpkss1.dll"
gemalto="C:\Program Files (x86)\Gemalto\Classic Client\BIN\gclib.dll"
opensc="C:\windows\system32\opensc-pkcs11.dll"
```

So, you don't need to program a complex UI. Only a simple sub-menu; plus the load of the config.

You like this "simple solution"?

**Comment by lars18th** [comment]
And two suggestions for the current "Please Select PKCS # 11 Library File" window:

1. Open by default in `C:\Windows\System32\` path... or best `%WINDIR%\System32\`.
2. Add more well-known wilcards to the list: `"*pkcs*.dll; *pks*.dll; gclib.dll"`, etc.

I hope you agree!

**Comment by NoMoreFood** [comment]
I'll integrate some of lars's last comment into a version in the next few weeks.

**Comment by NoMoreFood** [comment]
See https://github.com/NoMoreFood/putty-cac/commit/0cdbe284cc4d3f55f53f41b19c551a69bbca758f.  Will build a pre-release tomorrow.

**Comment by NoMoreFood** [comment]
For testing:

https://github.com/NoMoreFood/putty-cac/raw/48dc768d16b69fcf44b623f324f5f577fe967bf1/binaries/puttycac-0.70u5-installer.msi
https://github.com/NoMoreFood/putty-cac/raw/48dc768d16b69fcf44b623f324f5f577fe967bf1/binaries/puttycac-64bit-0.70u5-installer.msi

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Thank you! The improvements are nice.

Regarding the Gemalto (that doesn't use the Windows directory), I use this "hack":

- As an administrator in the command prompt, inside the "C:\Windows\System32" directory type: **mklink gemalto-pkcs.dll "C:\Program Files\Gemalto\Classic Client\BIN\gclib.dll"**.

Then you can load it in the _default_ directory as "aetpkss1.dll" and "opensc-pkcs11.dll" the _new_ "gemalto-pkcs.dll".

**Comment by jursed** [comment]
How about a simple registry entry with the library path? If the registry entry is

- not set, the "open file" dialog pops up every time.
- is set (manually, in regedit, i.e. "advanced use"), the path in the registry entry gets used.

Why bother: even with a symlink in `System32`, explorer first displays a million different subdirs, and the DLLs are at the very end. It's just an unnecessary extra step for what is (in practice) a daily task. So having Pageant just use whatever gets predefined somewhere (registry, text file, whatever) would make the UX slightly more bearable.

Just my two cents. :)

**Comment by lars18th** [comment]
Hi @jursed ,

> How about a simple registry entry with the library path?

I use it in a PORTABLE mode, so no registry please (or almost, not enforcing to use it).

> explorer first displays a million different subdirs, and the DLLs are at the very end.

Yes! It's a pain to select every DLL manually. So a _simple_ solution to bookmark them will be very useful.
In my opinion, a right-menu with a list, or _any other solution_ are valid. But we need something.

Please, @NoMoreFood consider some improvement in this area.
Thank you for your effort!

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Please, almost for the wildcards filters for reading the DLLs, add too this one `*p11*.dll`.
Some providers use this format name for his libraries.

So, apply `*pkcs*.dll;*pks*.dll;*p11*.dll;gclib.dll`
Thank you!

**Comment by NoMoreFood** [comment]
@lars18th At the very least, I'll include the additional filter in the new release.
