### ISSUE TITLE
Question: Automated retrieval of CAPI SSH keystring

### ISSUE THREAD

**Issue by kohawk41** [NoMoreFood/putty-cac#25]
Hello, 

I am trying to determine if there is any way to automate the retrieval of the CAPI string (ssh-rsa AAAAB3NzXX.......) from a smartcard/PKI infrastructure (AD or CA perhaps) or if it has the be retrieved from the card manually by the user each time. Thanks

**Comment by NoMoreFood** [comment]
Yes, this can be done.  I'll see if I can get you an example that I've used.

**Comment by kohawk41** [comment]
Hi @NoMoreFood , sorry to be a pest but wondering if you had any examples or guidance on how this could be accomplished? Thanks!

**Comment by NoMoreFood** [comment]
Sorry, I forgot about this.  Do you need something that handles ECDSA or just RSA?

**Comment by kohawk41** [comment]
Hi @NoMoreFood - no problem at all. I think just rsa. As long as we can pull the ssh-rsa pub key/capi string that would be a huge help. Thanks!

**Comment by NoMoreFood** [comment]
I will be posting some code on Script Center in the next few days.   I'll put a link here once I do.

**Comment by kohawk41** [comment]
Excellent! Thank you in advance

**Comment by NoMoreFood** [comment]
Finally got around to this.  Can you see if the attached works?  I still plan on putting on it on Script Center, but would like some initial feedback.  

`Get-CertificatesFromAuthority -Server 'CA-SERVER' -Authority 'CA' | Get-CertificateKeyString`

[CertificateTransformer.zip](https://github.com/NoMoreFood/putty-cac/files/1910449/CertificateTransformer.zip)

**Comment by NoMoreFood** [comment]
Closing due to non-responsiveness / inactivity.
