### ISSUE TITLE
Too many Certificates in pageant

### ISSUE THREAD

**Issue by JannoTjarks** [NoMoreFood/putty-cac#26]
Hi,

i want to use your pageant with cisco switches. But Putty showed this error message incomprehensibly, if the public-key is not present on the switch:
![2018-03-22_11h42_52](https://user-images.githubusercontent.com/33316737/37766083-2a39ea92-2dc6-11e8-84d5-6eb04445074d.png)
Putty does not attempt a "keyboard-interactive" auth as fallback.

**Comment by NoMoreFood** [comment]
So it works properly if the public key is present on the switch?

**Comment by JannoTjarks** [comment]
Yes.
I have a update to this issue. The Problem wasn't the switch or the pageant. After removing of unused certificates, it works. Are to many certs making errors?

**Comment by NoMoreFood** [comment]
Yes, this is a limitation of the SSH server, not PuTTY.  For example, in OpenSSH, I believe this is controlled by the MaxAuthTries parameter.  Basically PuTTY ships each public key one-by-one waiting for the server to accept one and send a challenge.  After a certain point, the SSH server stops asking.  I *believe* that if you use PuTTY (with Pageant) and you specify a certain certificate to use in PuTTY, it will try that certificate first before resorting to the arbitrary list available in Pageant.

**Comment by JannoTjarks** [comment]
Thanks for the very fast support.  Is there a possibility, to select certificates for the autoload? I installed many certs for my servers, but I need only the one from my smartcard for the switches in the end of the pageant list.

**Comment by NoMoreFood** [comment]
Sorry, that would require a completely separate user interface which I don't think I can support right now.  You could check Autoload, uncheck it, and then just remove the certs you don't care about.

**Comment by JannoTjarks** [comment]
Ok, thank you. I can understand, that a additional UI will make a lot of work.
