### ISSUE TITLE
PIV / CAC authentication for "pscp.exe" and "psftp.exe" not available?

### ISSUE THREAD

**Issue by ken-bell** [NoMoreFood/putty-cac#27]
I am told that although PIV/CAC auth works for "putty.exe" it does not for "pscp.exe" or "psftp.exe".

(The smart card manager reports that the card uses PKCS#1 SHA-256 with RSA encryption)

Is that in fact the case?  If not, any ideas on why this user is having problems with it would be appreciated.

Thank you.
Ken

**Comment by NoMoreFood** [comment]
Those utilities should work by using the '-agent' parameter and then using Pageant to authenticate the user.  Let me know if that doesn't work.

**Comment by NoMoreFood** [comment]
You can also use the -i parameter and specify the certificate to use:

`psftp -i CAPI:ba2f9207e40573cf3e0695ca7789ecc572a12391 user@host.com`

**Comment by ken-bell** [comment]
Thank you.  Using "Pageant" works perfectly.
