### ISSUE TITLE
Suggestion: Make a Chocolatey install package

### ISSUE THREAD

**Issue by RufusJWB** [NoMoreFood/putty-cac#28]
Would you mind, if I create a package for https://chocolatey.org/ ?

**Comment by RufusJWB** [comment]
Probably I could do with some GIT and PowerShell magic an automated build, but for the start I would build the package by hand. If there is an update, I would need to adapt the config files and build a new package.

**Comment by RufusJWB** [comment]
I built a package by hand and submitted it to chocolatey: https://chocolatey.org/packages/putty-cac/0.70-update40

**Comment by NoMoreFood** [comment]
Closing due to non-responsiveness.

**Comment by NoMoreFood** [comment]
@RufusJWB If you do not plan on updating the Chocolatey package, can you please remove it?  The new version out there has many security updates.

**Comment by RufusJWB** [comment]
Hi! I missed your original post. I'll update the package in the next days.

**Comment by RufusJWB** [comment]
I'll pushed an [update](https://chocolatey.org/packages/putty-cac/0.71) to chocolatey. It is waiting for approval.

**Comment by RufusJWB** [comment]
Version 0.71 is published under https://chocolatey.org/packages/putty-cac/0.71

**Comment by NoMoreFood** [comment]
@RufusJWB Version 0.72 is out.  Includes security updates.

**Comment by NoMoreFood** [comment]
@RufusJWB Version 0.73 is out. Includes security updates.

**Comment by RufusJWB** [comment]
0.73 is in the review process: https://chocolatey.org/packages/putty-cac/0.73

**Comment by RufusJWB** [comment]
btw: I updated to 0.72 directly after your message

**Comment by NoMoreFood** [comment]
@RufusJWB Another update, at your leisure.  Thanks!

**Comment by RufusJWB** [comment]
@NoMoreFood the updated version is pushed to chocolatey

**Comment by NoMoreFood** [comment]
@RufusJWB Can you pushed this latest version?

**Comment by RufusJWB** [comment]
done

**Comment by NoMoreFood** [comment]
@RufusJWB And yet another upstream update has been incorporated at your leisure.

**Comment by RufusJWB** [comment]
> @RufusJWB And yet another upstream update has been incorporated at your leisure.

On its way through the choco moderation: https://community.chocolatey.org/packages/putty-cac/0.76

**Comment by NoMoreFood** [comment]
@RufusJWB Would you mind updating chocolatey for 0.77.0.1?

**Comment by RufusJWB** [comment]
This is a problem since I've switched from Chocolatey to MS Winget and I don't have the Chocolatey tool chain anymore installed. I'll re-install it and build a new package. This will take some days.

**Comment by NoMoreFood** [comment]
@RufusJWB Sure, I can take it over - let me know what you need to do that.  I'm already doing the winget package and I imagine the process is similar.

**Comment by RufusJWB** [comment]
> @RufusJWB Sure, I can take it over - let me know what you need to do that. I'm already doing the winget package and I imagine the process is similar.

I have prepeared a step-by-step documentation under https://github.com/RufusJWB/puTTY-CAC-Chocolatey/blob/master/README.md . If you don't mind, I would set up a conference call with you when I prepare the next time a chocolatey package and we go through it together. What do you think?

**Comment by RufusJWB** [comment]
Or we create a GitHub Action to automatically build the chocolatey package. Did you ever do something like this before?

**Comment by RufusJWB** [comment]
@RufusJWB I glued everything together in a GitHub Action: https://github.com/RufusJWB/puTTY-CAC-Chocolatey/blob/master/.github/workflows/buildPackage.yml I'll create a PR to bring it together with this repro

**Comment by RufusJWB** [comment]
You will need to create a `secret` with the name 'CHOCOAPIKEY` which holds your Chocolatey API key.
