### ISSUE TITLE
putty-cac crash when capi or pkcs key loaded

### ISSUE THREAD

**Issue by HWataru** [NoMoreFood/putty-cac#29]
putty clashed when `set capi cert` or `set pkcs cert` button clicked.

![2018-06-18_17h50_08](https://user-images.githubusercontent.com/28978715/41526787-2e67a6aa-7320-11e8-95c3-0cc2c5255494.png)

an error is shown on event viewer

![2018-06-18_17h52_59](https://user-images.githubusercontent.com/28978715/41526929-9ba6cdd6-7320-11e8-90ea-c672ffc99ba5.png)

* Windows 10 1803
* putty-cac ver 0.7.3 and 0.7.4

**Comment by NoMoreFood** [comment]
Very odd.  Any special type of security software you have installed or other configuration options worth mentioning?

**Comment by NoMoreFood** [comment]
Also, did you install PuTTY using the MSI installer or are you running just the PuTTY downloaded from releases?

**Comment by HWataru** [comment]
I tried both msi installer and binary. I'll check my Security Software setting(I use webroot).

**Comment by NoMoreFood** [comment]
Ok, let me know.  I suspect it's something environmental since that's occurring when loading the DLLs necessary to do certificate / file selection.

**Comment by HWataru** [comment]
I checked my environment and finally found the issue came from my custom credential provider.
I'll comment if I get additional information about my bad application.

Thank you.

**Comment by NoMoreFood** [comment]
Thank you for the update.  I suspect this is may be due to the fact that that PuTTY (upstream) restricts how DLLs are loaded for security reasons.  If the custom credential provider is public and you want me to see if the crash is avoidable, please send me more information on how to download/install it.  I suspect you could avoid the error by placing the provider DLL and any of its dependencies in system32.

**Comment by HWataru** [comment]
FYI, my credential provider call Windows credential manager illegally when putty-cac show certificate list.
I fixed it and everything went well! Thank you.

**Comment by NoMoreFood** [comment]
Excellent.  Thanks for the update.
