### ISSUE TITLE
Putty-CAC cert/cert-capi.c is still using SHA1 which  newer OpenSSH servers will not accept. 

### ISSUE THREAD

**Issue by dengert** [NoMoreFood/putty-cac#30]
See the discussion on: [smartcard-openssh-and-putty-ssh](https://superuser.com/questions/1331684/smartcard-openssh-and-putty-ssh/1342180#1342180)

Note the same Yubikey 4 works via opensc-pkcs11.dll, but does not work via CAPI. The Yubikey 4 is a PIV like card and uses the Microsoft builtin smart card drivers. 

OpenSSH servers no longer accept SHA1 signatures. Putty-CAC appears to still be trying use SHA1 in cart-capi.c

It looks like cert-capi.c is defaulting to using `CALG_SHA1` in line 86, or the code at line 111:
`tInfo.pszAlgId = NCRYPT_SHA1_ALGORITHM;`    

As I don't have a good way to debug Putty-CAC here is some of the putty-log, openssh debug and a snipit which show up twice. I think from lines70 and 71. 
```
   CryptSignHash(hHash, pProviderInfo->dwKeySpec, NULL, 0, NULL, &iSig) != FALSE &&
   CryptSignHash(hHash, pProviderInfo->dwKeySpec, NULL, 0, pSig = snewn(iSig, BYTE), &iSig) != FALSE)
```
But then in the breakpoint hits and the siglen = 0 which is not good. 

[openssh-putty-cac.txt](https://github.com/NoMoreFood/putty-cac/files/2216613/openssh-putty-cac.txt)
[putty.log](https://github.com/NoMoreFood/putty-cac/files/2216609/putty.log)

![yubikeyicant-do](https://user-images.githubusercontent.com/865329/43040903-bd183a1c-8d16-11e8-95fa-a9acddd17d57.PNG)

**Comment by NoMoreFood** [comment]
Thanks for the report.  I'll try to take a look soon.  I believe you can install Visual Studio Community edition if you're interested in debugging.  

Two questions:

1) Do you know what version of OpenSSH stopped supporting SHA1 signatures? 
2) Are you able to reproduce using a PuTTY generated key?  Much of the PuTTY-CAC certificate code was modeled after what the normal PuTTY code was doing so I'm curious if it has the same problem.

Thanks!

**Comment by NoMoreFood** [comment]
Trying to reproduce on OpenSSH 7.7.  Do you have an example sshd_config you can attach where you see the issue?  Also does your authorized_keys file have a different identifier (something other than ssh-rsa)?

**Comment by NoMoreFood** [comment]
Looking at the upstream (PuTTY) code, I don't think it supports ssh-rsa-sha256 or ssh-rsa-sha512 signatures at all.  It doesn't even get to the point of trying to sign in my testing.  Are you certain that it works with PKCS? I don't do anything SHA256 related in PKCS either.

**Comment by dengert** [comment]
I am going to close the issue for now.

There is something about the Yubico 4 token that Windows 10  PRO 1803  does not like. The MessageBox above is displayed even when trying to use `certinfo -v -scinfo` 
The token used to work with CAPI and it works via PKCS\#11 using opensc-pkcs11.dll.  

The NIST DEMO card #2 works fine with Putty-CAC. 

I did get VS2017 with github extension to build putty.exe and debugging shows the 2 MessageBoxes above are from failures in: 
```
if (CryptAcquireContextW(&hCryptProv, pProviderInfo->pwszContainerName,
			pProviderInfo->pwszProvName, pProviderInfo->dwProvType,
			(pProviderInfo->dwFlags & CRYPT_MACHINE_KEYSET) ? CRYPT_MACHINE_KEYSET : 0) != FALSE)
```
and 
```
else if (NCryptOpenStorageProvider(&hNCryptProv, pProviderInfo->pwszProvName, 0) == ERROR_SUCCESS &&
			NCryptOpenKey(hNCryptProv, &hNCryptKey, pProviderInfo->pwszContainerName, pProviderInfo->dwKeySpec, 0) == ERROR_SUCCESS)
```
The code goes on to send the response but with a zero length signature, and garbage for the signature.
The code should save the return codes and send to putty.log, and not send a bogus response.  

It never got to the code to try and use SHA1.

The NIST DEMO card #2 works fine with Putty-CAC even with the sha1.  Enventialy OpenSSH will not accept sha1 signatures, and Putty-CAC should be able to use SHA2-256.

**Comment by NoMoreFood** [comment]
Just wanted to let you know I confirmed with the PuTTY folks that SHA2 RSA signing is not supported yet.  So until it is, it'll be tough to support in PuTTY-CAC.

**Comment by dengert** [comment]
My Windows 10 PRO system had the Yubico Minidriver package installed. After uninstalling it it, Putty-CAC started working. The Yubico Minidriver is not really needed for PIV cards or PIV like tokens because Microsoft has a built in driver for PIV. Apparently their Minidriver can't handle something and that was causing the MessageBox to be displayed. But since Putty-CAC whas not handling the failures and when ahead and sent a bogue response to SSHD, the problem was not obvious.

**Comment by NoMoreFood** [comment]
@dengert So I took a look at the logic.  What do you think would be a better "reaction" for PuTTY in this scenario as opposed to sending back a packet with no signature.  To just drop the connection?

**Comment by dengert** [comment]
Yes, and an error to the PuTTY log showing the return code from the Microsoft routines that failed.
