### ISSUE TITLE
Autoload Certs loads too many certs

### ISSUE THREAD

**Issue by opoplawski** [NoMoreFood/putty-cac#31]
We have users with lots of different certificates (multiple YubiKeys, VPN certs, etc.).  It's nearly impossible for users to determine which certificate to add to pageant/putty, and "Autoload Certs" loads all of the available certs which leads to errors like:
```
The smart card cannot perform the requested operation or the operation requires a different smart card.
```
We need a way to load just the certificate for the current user from the connected smart card.

**Comment by opoplawski** [comment]
I think PuTTY-CAC really needs to interact with the smart card.  This is what ssh-agent does on Linux via opensc-pkcs11.so.  As it stands I'm presented with a list of 5 certificates, two of which are present on the card.  If others are selected I get the error above.  This really isn't workable as it stands.

**Comment by NoMoreFood** [comment]
It works for thousands of people as it stands.  You may want to consider cleaning up your certificate stores.  CAPI can also hit tokens that don’t go through the smart card device functions so I’m not going to add a feature that could limit functionality.

How about my idea?  Are the certificates of interest marked for Smard Card Logon explicitly?

**Comment by NoMoreFood** [comment]
The next release (available in the next few weeks) will provide an option to screen out expired and/or certificates that are not marked explicitly for smartcard logon

**Comment by opoplawski** [comment]
This is becoming an absolute nightmare for us.  We have people with multiple smart-card and multiple identities and it's really hard to get pageant to load the proper certificate.  I wish I had time to look into adding the proper functionality to pull the cert from the inserted smart card, but I don't at the moment :(.
