### ISSUE TITLE
Problem with SSH Agent Forwarding when start with Putty-CAC+Pageant-CAC

### ISSUE THREAD

**Issue by ohaya** [NoMoreFood/putty-cac#34]
Hi,

We are trying to setup an SSH Agent Forwarding situation where we "start" by using Putty-CAC (with Pageant-CAC running and loaded with the key) to get to what I call a "jump machine" (this is connection/authentication is implemented via a COTS product).

Then, onnce we are logged into the jump machine, we have an SSH private key in the .ssh dir and the corresponding public key in the .ssh of the target (==target1), and the user can SSH to the the 'target1' machine without entering a password.  In the same way, we have agent forwarding configured, so the user can then SSH to the 2nd target (==target2) machine, again with no password.

However, we are having problem with that 2nd hop (to target2) and the user gets prompted for the password :(....

NOTE that if we use just Pageant and Putty, and Putty directly to the jump machine, then the SSH to target1, and then the next SSH to target2, works fine, with no password being entered.

To be clear, I don't know if this is a problem with Putty-CAC... I don't actually know WHAT the problem is, but I am posting this here, to try to maybe get some information.

In a test, I have recorded the same login chain, using both approaches (Putty+Pageant+forwarding) vs. (Putty-CAC+Pageant-CAC+COTS) and using "SSH -vvvv" and comparing the output side-by-side, which I am attaching.

The difference seems to be that the one that works has this:

debug2: key: imported-openssh-key (0x7f109753bc00)
debug2: key: /home/centos/.ssh/identity ((nil))
debug2: key: /home/centos/.ssh/id_rsa ((nil))
debug2: key: /home/centos/.ssh/id_dsa ((nil))
debug2: key: /home/centos/.ssh/id_ecdsa ((nil))
debug3: Wrote 68 bytes for a total of 1317

whereas the one that does not work has just this:

debug2: key: /home/centos/.ssh/identity ((nil))
debug2: key: /home/centos/.ssh/id_rsa ((nil))
debug2: key: /home/centos/.ssh/id_dsa ((nil))
debug2: key: /home/centos/.ssh/id_ecdsa ((nil))
debug3: Wrote 68 bytes for a total of 1317
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password

i.e., the one that does not work is missing this line:

debug2: key: imported-openssh-key (0x7f109753bc00)

the "imported-openssh-key" is the private key, so it appears that on the scenario that is not working, for some reason, the SSH is not getting the private key passed to it or something.

Does this make any sense?

Thanks,
Jim
[log.txt](https://github.com/NoMoreFood/putty-cac/files/2390263/log.txt)

**Comment by NoMoreFood** [comment]
I've never played with forwarding much.  Are you running the ssh on the Linux side with -A to enable agent forwarding?

**Comment by ohaya** [comment]
Hi,

On each of the "intermediate" CENTOS machines, I have the "forwarding" parameters in the /etc/ssh/ssh_config and in the /etc/ssh/sshd_config uncommented and set to "Yes":

/etc/ssh/ssh_config ==> ForwardAgent yes
/etc/ssh/sshd_config ==> AllowAgentForwarding yes

It is a kind of strange problem, because like I said, if I "start" with just Putty+Pageant and "putty directly" to the jump machine, the ssh "chaining" works all the way through to the last target.  Also, even when starting with Putty-CAC+Pageant-CAC we can get to the jump machine and chain through to the first target without password, but when we then try to SSH to the second target, we get prompted for a password.  

Also, like I said earlier, I am not 100% sure "where" the problem is, i.e., I don't know for sure if this is due to Putty-CAC, but I'm kind of "thrashing around" try to find a solution.

**Comment by ohaya** [comment]
Hi,

Ok, thanks.

On CENTOS 6.8, OpenSSH_5.3p1. (the jump machine and one of the target machines is CENTOS 6.8)

On CENTOS 7.5, openssh-7.4p1

I get the same behavior whether I go to the jump machine, then to CENTOS 6.8, then try to go to CENTOS 7.5 machine, OR if I go to the jump machine, then CENTOS 7.5 machine, then try to go to CENTOS 6.8 machine.

Jim

**Comment by jcyph3r** [comment]
This is expected behavior. Further explanation of the issue here.
http://unixwiz.net/techtips/ssh-agent-forwarding.html#sec
