### ISSUE TITLE
x509 certificate lookup failure before signing in some nistp521r1 public key.

### ISSUE THREAD

**Issue by tanepod** [NoMoreFood/putty-cac#35]
Hi,
I'm developing PKCS#11 token and testing it.
In the test, I found some problems in nistp521 operation.
https://github.com/NoMoreFood/putty-cac/blob/ffd5c719357b896d5ed8298c24fc0807c7bae07f/cert/cert_pkcs.c#L69

The nistp521r1 ecpoint (x, y) has the length of 521 bits or 65byte+1bit for each x and y.
In some case, a effective size of x is 65 bytes and of y is 66 bytes, then pkcs_lookup_token_cert() will fail.
 
Furthermore, puttygen always puts 66bytes x2 long into PEM EC Public Key regardless of x,y length.
If both x and y are 65byte long and public key in certificate is formed 66byte long, this routine doesn't work properly.

I've attached files in zip:
nistp521_65and66_pub.pem - EC public key generated by OpenSSL. x=65bytes, y=66bytes
nistp521_65byte.ppk - putty key generated by puttygen, x and y are both 65bytes but 0 paddings exist.
nistp521_65byte_privkey.pem - private key of nistp521_65byte.ppk, generated by generated by puttygen
nistp521_65byte_pubkey.pem - public key of nistp521_65byte.ppk, generated by generated by puttygen
nistp521_65byte_cert.pem - certificate of nistp521_65byte.ppk, generated by OpenSSL
[nistp521_keys.zip](https://github.com/NoMoreFood/putty-cac/files/2481523/nistp521_keys.zip)

Thanks,
masayuki

**Comment by tanepod** [comment]
Hi, 
I found that ecdsa_public_blob() in sshecc.c calculates the point length correctly as follows:
-EC_EDWARDS
  pointlen = ec->publicKey.curve->fieldBits / 8;
-EC_WEIERSTRASS:
 pointlen = (bignum_bitcount(ec->publicKey.curve->p) + 7) / 8;  

How about adopting this way?

Thanks,
masayuki

**Comment by NoMoreFood** [comment]
Excellent write-up; I'll try to take a look tonight.

**Comment by NoMoreFood** [comment]
I built some changes based on your comments, but I have not had time to test them whatsoever.  If you can try to see if it fixes the issue, that'd be great: https://github.com/NoMoreFood/putty-cac/blob/master/binaries/puttycac-0.70u6.zip

**Comment by tanepod** [comment]
Hi, 
Thanks for your quick response!

Unfortunately, putty.exe of version 0.70u6 doesn't work property.
I've checked source and found your misunderstanding in ECPoint uncompressed form representation and
leading bugs  in reverting byte ordering.

I've attached verified source and written background on below.
The file is based on 0.70u5 and only changed line69
[cert_pkcs.zip](https://github.com/NoMoreFood/putty-cac/files/2490515/cert_pkcs.zip)

There are three important points in 0.70u6.
First, EC_EDWARS support codes are not needed. Second, the length of x and y in ECPoint representation must be same. And last, callings of cert_reverse_array().

You know, EC_EDWARS is used in Ed25519 (alg->name of "ssh-ed25519"), and EC_WEIERSTRASS is used in ECDSA (alg->name of "ecdsa-sha-nistp256",  "ecdsa-sha-nistp384" or "ecdsa-sha-nistp521").
So,  in the block of `if (strstr(userkey->alg->name, "ecdsa-") == userkey->alg->name)` ,
we suppose curve type is EC_WEIERSTRASS. 
（By the way, PKCS#11 does NOT support Ed25519 so far.）

Next, ECPoint representations. SEC 1 (or ANSI X9.62) defines it in section 2.3.3 "Elliptic-Curve-Point-to-Octet-String Conversion" like following:

> Output: An octet string M of length mlen octets where mlen = 1 if P = O, mlen = L +1
if P != O and point compression is used, and mlen = 2 L + 1 if P != O and point
compression is not used.
> ...
> Actions: convert M to an elliptic curve point P as follows:
> ...
> 3 If P = (xP , yP ) != O and point compression is not being used, proceed as follows:
> 3.1 Convert the field element xP to an octet string X of length L octets using the
conversion routine specified in Section 2.3.5.
> 3.2. Convert the field element yP to an octet string Y of length L octets using the
conversion routine specified in Section 2.3.5.
> 3.3. Output M = 0x04 || X || Y .

In the context, mlen is the byte length of the ECPoint buffer and L means byte count of p which is fieild elements (Fp).
For example, the field elements p of nistp521 is 521 and the byte count is 66.
In PuTTY project, the field element p is stored as Bignum p of struct ec_curve in ssh.h.

cert_pkcs_sing() adotps uncompressed form as putting 0x04 on the head of the buffer at line 73, 
the length of x and y must be same and be L by action 3 and 3.2.
So, we only need to change the calcuration of L.

Last callings of cert_reverse_array() are simple bugs. Fixed codes are below.
```
cert_reverse_array(1 + pDataToEncode, iKeySizeX);
cert_reverse_array(1 + pDataToEncode + iKeySizeX, iKeySizeY);
```
But, now we now that iKeySizeX and iKeySizeY are same as iKeySize, then keep 0.70u5 codes.

Thanks,
masayuki

**Comment by tanepod** [comment]
I've tested new binaries. They work!

**Comment by NoMoreFood** [comment]
Alright, I'll do some of my own testing this weekend and if it looks good, I'll do a release.

**Comment by NoMoreFood** [comment]
This is fixed in latest release; closing.
