### ISSUE TITLE
Question: How does the certificate gets converted into ssh-rsa string?

### ISSUE THREAD

**Issue by leiocalyx** [NoMoreFood/putty-cac#36]
Hello,

I would like to know more about how is the ssh-rsa string is generated from the certificate. 

The main question is: what algorithm is used for certificate convertion and how does it work with openssh? The most confusing part, is that it seems to be not certificate authentication per se... but it still works somehow... 

Also, the `CAPI:e495b3a063cd6a779ea810007d066ecd27da17f9` part seems unimportant (I've deleted it, and the auth still worked), is it just there so that you could more easily distinguish the keys in the authorized_keys file?

**Comment by NoMoreFood** [comment]
So you are correct that it's not certificate-based authentication.  It's public key authentication and we just use the certificate as the standardized holder of the public key (and a means to interface to a private key that can be securely stored on a token).   The SSH protocol does support real certificate authentication as detailed in RFC6187 but it's not overly popular since it requires more server-side setup.

You are correct that the CAPI part of the string is unnecessary.  The part of the string is just a comment; you can literally put anything there.  In terms of the RSA keystring, here's an exert from one of my scripts that uses PowerShell and a DotNet certificate object to construct the string (see https://github.com/NoMoreFood/putty-cac/blob/master/tools/CertificateTransformer.ps1).

```
$PublicKey = $CertObject.PublicKey.Key

$KeyType = 'ssh-rsa'
$Params = $PublicKey.ExportParameters($False)
$Header = [System.Text.ASCIIEncoding]::ASCII.GetBytes($KeyType)

$Writer.Write([System.Net.IPAddress]::HostToNetworkOrder($Header.Length))
$Writer.Write($Header)

$Writer.Write([System.Net.IPAddress]::HostToNetworkOrder($Params.Exponent.Length))
$Writer.Write($Params.Exponent)

$Writer.Write([System.Net.IPAddress]::HostToNetworkOrder($Params.Modulus.Length + 1))
$Writer.Write([byte]0x0)
$Writer.Write($Params.Modulus)
...
$KeyType + ' ' + [System.Convert]::ToBase64String($Stream.ToArray())
```

**Comment by NoMoreFood** [comment]
Did that answer your question? @leiocalyx

**Comment by leiocalyx** [comment]
Kind of, I've tried looking at the code, but I still don't understand what _exactly_ is happening. 

I managed to select the certificate with Get-ChildItem and do the same thing it does in the gui, but is there a way I can add something like Write-Host to see the transformation happening step by step?

**Comment by NoMoreFood** [comment]
To be clear, the code I posted you is not what runs when running PuTTY CAC, but it is functionally equivalent.  PuTTY is all C code so there's no 'Write-Host' command.  If you want/need to see _exactly_ what happens, you're best bet is to get Visual Studio and step through the debugger.

**Comment by NoMoreFood** [comment]
@leiocalyx Please close this issue unless you have any additional questions.

**Comment by leiocalyx** [comment]
I still don't understand what exactly happens that this
`-----BEGIN CERTIFICATE-----
MIICpzCCAY+gAwIBAgIJANw2JSwYRqw4MA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCEtyaXN0aW5hMB4XDTE4MTEwOTEzMjY1NloXDTE5MTEwOTEzMjY1NlowEzER
MA8GA1UEAwwIS3Jpc3RpbmEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDl+dnmhT4JPWnXnTpcK1gTJLZ/wPz4OGE+fnR+hH0hqp06FRz/nvtf2bi1dGUh
q1d8qDQnO8vGJMc0lFlhyhzTHXo2iW0lqG/kOeR5ggfOCRsSbNXVPVlRM0cNG6MF
SwE5apVDJy6GjSEpAAHN+Nz07Ng89ZxhhNXKR69KFnZGHSqqys/sgldGMSoQmOz1
/njhL4cCW6c2HeqPHPCcgsv7Lv0p3A9VpyjCKVS3WCkpUs6CMFUTumJDqLXg1btX
Gv2CnTBELuLP0qPJXzpeKnFEaeWVx3FIgHNbEiXHOqcaag8hlWrSKOJdN6Lju9xm
MYymxbuOwlM4QFKZjD6PlqdbAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAH914lZZ
9jAMm+zs7AzPVEAh67LEI14vtk/MXwUbZd6wYBrtdAgGTRe7ZCRGL46Si3Nm0PB/
QukCEWVZltgEykTQuEVKpyxrfKQalRxsoAScw8FQhaDhoBaART78LUZZKR+GMCvn
7ZtWnQaBr7nqEhlSjAyI6ItSYb9nt33y1m8Y0lzlfVyPx0o+g4bbMOwht2YgsmdP
gPJxpe+U/F2kKb386A6ZSBvgUl6qk2t0iVB+fXSK94IT+fk9M5bP8LeIh/T9MYx7
gZbcvBFYovPfFCgXfNRxrjp2eiao82S1lpAYJbqTwtZEFMt7u+X9jg6pVUzRQ32O
r1ux7UO3c9De8xI=
-----END CERTIFICATE-----`
turns into this 
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDl+dnmhT4JPWnXnTpcK1gTJLZ/wPz4OGE+fnR+hH0hqp06FRz/nvtf2bi1dGUhq1d8qDQnO8vGJMc0lFlhyhzTHXo2iW0lqG/kOeR5ggfOCRsSbNXVPVlRM0cNG6MFSwE5apVDJy6GjSEpAAHN+Nz07Ng89ZxhhNXKR69KFnZGHSqqys/sgldGMSoQmOz1/njhL4cCW6c2HeqPHPCcgsv7Lv0p3A9VpyjCKVS3WCkpUs6CMFUTumJDqLXg1btXGv2CnTBELuLP0qPJXzpeKnFEaeWVx3FIgHNbEiXHOqcaag8hlWrSKOJdN6Lju9xmMYymxbuOwlM4QFKZjD6Plqdb CAPI:e495b3a063cd6a779ea810007d066ecd27da17f9 CN=Leiocalyx`

But I guess I'll try again after learning more about crypto and/or powershell...

**Comment by NoMoreFood** [comment]
Simpy put, the first value is a base-64 string.  That's converted to binary and then the modulus and export part of the public key in that binary data are transferred to a different binary structure which is converted back to base-64.  It's not complicated, but it does require a broad understanding of a variety of areas.
