### ISSUE TITLE
Request: Pageant icon different color

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#44]
Hi,

As I need to run different versions of Pageant, it will be desirable if the CAC version will have a different icon. For example, one whith a green variation over the stock.

You agree?

**Comment by NoMoreFood** [comment]
Given the very nuanced use case and the fact there are many tutorials with screen shots that reference the icon, I am not willing to change this.  You may want to reach out some of the other forks you use to see if they are willing.
