### ISSUE TITLE
pageant and putty crash when add dll library

### ISSUE THREAD

**Issue by rumanzo** [NoMoreFood/putty-cac#45]
pageant and putty crash when add dll library
I open pagent, click "Add PKCS Cert", select opensc-pkcs11.dll, and click OK in windown form "PuTTY: Select Certificate for Authentication"
Same situation in putty if I add dll library
I have windows 10 pro with all last updates.
[AppCrash_pageant.exe_38d025ccead485afa7be298d5c4356469c38aa8_bc63c0b2_246b0da0.zip](https://github.com/NoMoreFood/putty-cac/files/3570888/AppCrash_pageant.exe_38d025ccead485afa7be298d5c4356469c38aa8_bc63c0b2_246b0da0.zip)

**Comment by NoMoreFood** [comment]
Is this the latest available opensc dll?

**Comment by rumanzo** [comment]
OpenSC-0.19.0 - latest version (and quite old at the same time)

**Comment by NoMoreFood** [comment]
I'm not able to reproduce the issue simply by loading the library.  If I provide you a debug version of the executable, can you provide me a dump file when the application crashes?  It's possible the crash is inside the PKCS library itself.

**Comment by rumanzo** [comment]
Sure, i will test it.
Earlier I could add a library once out of 15 times. Nothing changed (version of opencs and agent), but now I can't. 
it seems to me that this could be due to windows updates, but i'm not sure

**Comment by NoMoreFood** [comment]
Try attached.  I'll need the resultant .dmp file from your system.
[putty-debug.zip](https://github.com/NoMoreFood/putty-cac/files/3571984/putty-debug.zip)

**Comment by rumanzo** [comment]
[putty_n.zip](https://github.com/NoMoreFood/putty-cac/files/3572096/putty_n.zip)

**Comment by NoMoreFood** [comment]
Looks like the crash may be in a module called "BLEtokenCredentialProvider.dll".  Googling reveals it might be a buggy bluetooth driver that installs a custom credential provider (which are automatically enumerated by the dialog that gives you the certificates to select).  Can you try renaming this file to see if it addresses the issue?

**Comment by rumanzo** [comment]
You are 100% right. I renamed the file and the dll and key was added without any problems. And I found a similar problem on targeted search - https://serverfault.com/questions/758919/rdp-crashes-after-entering-password/758920#758920 . I do not know how the bluetooth driver is involved in this problem, but it is. Thank!
