### ISSUE TITLE
OpenPGP 4096bit key and pageant-cac support 

### ISSUE THREAD

**Issue by mti-sk** [NoMoreFood/putty-cac#47]
Hi,
I have a question about using OpenPGP token (Yubikey FIPS) and pageant-cac via the opensc-pkcs11 library (os: win10): 
In the OpenSC Forum, I received information that pageant-cac does not support 4096bit keys? 
If so, why this restriction? 
Will 4096bit key support be added in the future?
If a 4096bit key is stored on the token, the pageant displays a message that there is no available key on the card. For 2048bit OpenPGP keys I haven't tried it yet. 
I know that 4096bit OpenPGP keys can be put into a putty via the gpg-agent (GnuPGP), but because of exclusive access to the token it is useless to me. (I need to use one Token at the same time in PKCS11 mode [VPN connection] and OpenPGP mode [ssh connection]).

**Comment by NoMoreFood** [comment]
I do not have a hardware token to explicitly test a 4096-bit RSA key.  However, I tested a 4096-bit RSA key using CAPI software-based key and it worked just fine.  The CAPI subsystem doesn't actually care whether the private key is stored in hardware or software so 4096-bit definitely works with CAPI-based keys using PuTTY-CAC or Pageant-CAC.  I don't have a way to test software-based keys using PKCS, in general, but I can tell you there is nothing preventing the use of arbitrary key lengths that I know of.  

Are you certain your token actually supports 4096-bit keys?  I noticed this on the YubiKey site:
"The OpenPGP configuration will accept data in the following formats and lengths: Key - One RSA key, up to 4096 bits (**limited to 2048 on the FIPS series devices**)." Reference: https://support.yubico.com/support/solutions/articles/15000011059-yubikey-fips-series-technical-manual

**Comment by mti-sk** [comment]
Yubikey FIPS supports key generation up to RSA 3072bit, but you can also generate a 4096bit key externaly (gnuPG tool) and import it to the token. my 4096bit key on the Yubikey FIPS token works only through gnuPG (but that's not for me because of the exclusive gnupg lock, as I wrote before). otherwise I'd like to look at CAPI too: I don't know how to access the openpgp key via this interface. And what about you ?

**Comment by NoMoreFood** [comment]
Usually you need the card to be recognized by a minidriver.  After a quick google search, you might be able try this: https://www.mysmartlogon.com/products/openpgp-card-mini-driver.html

**Comment by mti-sk** [comment]
I use an openpgp library from the OpenSC project. I see the keys from command-line, but when try accessing to token via pageant-cac, I see only one key on token, which is 2048bit and not yet openpgp, but an X.509 openVPN certificate.

**Comment by NoMoreFood** [comment]
My previous message was referring to how you might be able to see if it works using CAPI.  If possible, send me the two certificates associated with your keys and I'll see if they are enumerated properly on my system.

**Comment by mti-sk** [comment]
I'm sending some logs that might be helpful.
No matter what I have the keys, if there is a way to use them, I am ready to generate the keys again.
There is a possibility to debug pageant-cac? Maybe you can figure out why he's not showing my keys.

**gpg (GnuPG) 2.2.17; Copyright (C) 2019 Free Software Foundation, Inc**.

Secret key are available.

pub  rsa4096/2BF800FFBCF14448
     created: 2019-10-25  Valid to:              usage: C
     trust: absolutní     platnost: absolutní
ssb  rsa4096/AD3732B58B9B94EC
     created: 2019-10-25  valid to:       usage: S
      card number: 00023424244242
ssb  rsa4096/08DAF2E6838DD713
     created: 2019-10-25  valid to:             usage: E
     card number: 00023424244242
ssb  rsa4096/9954BD2F03F69456
     created: 2019-10-25  valid to:      usage: A
     card number: 00023424244242
[  absolut ] (1). mti-sk <mti-sk@xxxxx.cd>

**C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe -T**
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 OTP+U2F+CCID 0
  token label        : User PIN (OpenPGP card)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 00023424244242
  pin min/max        : 6/127
Slot 1 (0x1): Yubico Yubikey 4 OTP+U2F+CCID 0
  token label        : User PIN (sig) (OpenPGP card)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         :  00023424244242 
  pin min/max        : 6/127

**C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --login --test**
Using slot 0 with a present token (0x0)
Logging in to "User PIN (OpenPGP card)".
Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (Encryption key)  -- can't be used for signature, skipping
  testing key 1 (Authentication key)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (4096 bits, label=Authentication key) with 1 signature mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (Encryption key) -- can't be used to sign/verify, skipping
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (Encryption key)
    RSA-PKCS: error: PKCS11 function C_Decrypt failed: rv = CKR_ARGUMENTS_BAD (0x7)
Aborting.

**Comment by NoMoreFood** [comment]
Can you actually send or attach the Base 64 / DER encoded certificate file(s)?

**Comment by mti-sk** [comment]
Hi,

Maybe I've already figured out why my openpgp certificate can't be used via pageant-cac.
Before, I used gpg-agent (from gnuPGP) as an ssh agent and everything worked fine. **OpenSC library, but probably can't read my certificate from the Yubico token (see below:Invalid ASN.1 report)** By the ssh key string, I recognized that using the gpg-agent I am using a certificate on slot number 3 (they have the same public parts). Now I turn to the openSC project for help.

**log:**
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe --read-ssh-key 1
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACA ... NVE5h9/9P2Oq4yZHDFxD79F2Ev+Jqx1w== Signature key

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe --read-ssh-key 2
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACA ... 1DqakYxwd/+cxV/tKQFMT8nAUnf5G1Q== Encryption key

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe --read-ssh-key 3
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
**ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACA ... hRq7zeQwEpOT3BxlU7lAyIPlA5Q== Authentication key**

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe -r 1
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
Certificate with ID '1' not found.

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe -r 2
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
Certificate with ID '2' not found.

**C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe -r 3
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 0
Certificate read failed: Invalid ASN.1 object**

**Comment by mti-sk** [comment]
Hi,
everything wrong. The procedure described has proved to be incorrect. On the openPGP card, there are no certificates but only keys. The gnuPG and agent-gpg library emulates pageant, but as putty keys, not as certificates.
The OpenSC and PKCS11 libraries can access an openPGP card, but keys are available, not X509 certificates. At this point, it looks like a requirement to add functionality. Do you think it would be possible to modify pageant-cac to read keys through PKCS11 as putty keys. This would make it possible to use openPGP cards with pageant-cac.
thank you for your time. best regards.

**Comment by mti-sk** [comment]
sending some outputs to better understand the openpgp token:
today it is mainly Yubikey and Nitrokey
$pkcs11-tool.exe -L
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 OTP+U2F+CCID 0
  token label        : OpenPGP card (User PIN)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : XXXXXXXX
  pin min/max        : 6/127
Slot 1 (0x1): Yubico Yubikey 4 OTP+U2F+CCID 0
  token label        : OpenPGP card (User PIN (sig))
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized, user PIN locked
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 000XXXXXX
  pin min/max        : 6/127

$pkcs11-tool.exe -O
Using slot 0 with a present token (0x0)
Public Key Object; RSA 4096 bits
  label:      Encryption key
  ID:         02
  Usage:      encrypt, wrap
  Access:     none
Public Key Object; RSA 4096 bits
  label:      Authentication key
  ID:         03
  Usage:      encrypt, verify, wrap
  Access:     none

**Comment by mti-sk** [comment]
Hi,
The only way to use the keys from the token under windows that I found (link, see below) is to save the self-signed certificate on the token.
Creating a signature is only possible on Linux(under win ssl via pkcs11 don't work )
1.Create self-signed certificate:
$openssl req -engine pkcs11 -new -key "pkcs11:object=MyKeyPairOnToken"
-keyform engine -out myCert.pem -days 3650 -outform pem -x509 -utf8
2.store certificate on token:
$pkcs15-init --store-certificate myCert.pem --id 00 --verify-pin

This certificate can then be loaded into pageant-cac.

Note: using windows does not work with keys from the token under openSSH (pkcs11 is unsupported) and pageant-cac only takes certificates, not keys via PKCS11.

Link:
https://zerowidthjoiner.net/2019/01/12/using-ssh-public-key-authentication-with-a-smart-card

**Comment by NoMoreFood** [comment]
Glad you found out how to associate the keys with a certificate.  Does 4096-bit work as expected?

**Comment by mti-sk** [comment]
YES, 4096bit keys work, but not if they are OpenPGP.
The problem here is not with key length, but with the use of an OpenPGP card in general.

In the experiments I quite forgot something very important. You can create a certificate for a pair of keys, but you do not have how and where to store it with an openPGP card. During testing, however, I changed the OpenPGP card (token) with Nitrokey HSM, where you can store x509 certificates. It is still annoying that the OpenPGP card cannot be used to connect ssh (with Putty under WIN) without a gpg-agent.

**Comment by NoMoreFood** [comment]
No further action planned on this issue so closing.
