### ISSUE TITLE
"PuTTY could not load the selected PKCS library" when it is not even supposed to.

### ISSUE THREAD

**Issue by jmyreen** [NoMoreFood/putty-cac#49]
I used PuTTY-CAC using a a smart card and the OpenSC PKCS library. Then I decided to skip OpenSC because on Windows it's not really needed and not using it means one less (unsigned) package to install. So I uninstalled OpenSC and tried to use the MS CAPI instead.

Now, no matter how many times I try to remove any certificate using "Clear Cert" in the PuTTY configuration (which says "<no certificate installed>") or using "Remove" in Pageant, which does not list any certificate, I still get an error dialog saying message "PuTTY could not load the selected PKCS library. Either the file is corrupted or not appropriate for this version of PuTTY. [...]".

Obviously, the library file is "corrupted", since it is uninstalled. The bug is that there does not seem to be any way to get rid of the error message using either the PuTTY or Pageant user interface.

The only way I have found to get out of this situation is to delete the CAPICertID registry key, which has a value starting with "PKCS" and ending with the path to the (now non-existent) "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll".

**Comment by NoMoreFood** [comment]
What version of PuTTY CAC are you using?  Here's what I tried with 0.73:

1) Created and saved a new configuration that utilizes a certificate via a PKCS library.
2) Closed PuTTY.
3) Renamed the PKCS library to something else.
4) Opened PuTTY and loaded the configuration.
5) Navigated to the Cert menu and clicked 'Clear Cert'.

The behavior was as expected - the dialog said '<no certificate selected>' without any error.  I do get the error you mention when clicking 'View Cert' which makes sense given it needs the library to load the certificate.  Looking at the code (below), the 'Clear Cert' button shouldn't actually do anything with the PKCS library when doing 'Clear Cert'; it just clears out the registry entry.  Are my repro steps accurate?

```
// handle certificate clear button press
if (ctrl == certd->cert_clear_button && event == EVENT_ACTION)
{
	dlg_text_set(certd->cert_thumbprint_text, dlg, "<no certificate selected>");
	conf_set_str(conf, CONF_cert_certid, "");
	conf_set_bool(conf, CONF_try_cert_auth, 0);
	dlg_checkbox_set(certd->cert_auth_checkbox, dlg, 0);
}
```

Can you give me a registry dump of one of your connections that caused the issue?

**Comment by jmyreen** [comment]
I think I made a mistake when configuring the session. The PuTTY configuration system is not very intuitive. I tried again, this time meticulously loading the session, making the changes, and carefully making sure the session name is selected before pressing the Save button. By doing this I got the certificate change to work, and could not reproduce the problem. Sorry for your wasted time.
