### ISSUE TITLE
Wrong string used to determine if argument is -savecertlist or -savecertlistoff

### ISSUE THREAD

**Issue by jmyreen** [NoMoreFood/putty-cac#50]
https://github.com/NoMoreFood/putty-cac/blob/5eb85eb435644be4bffcb4d909e2cc12df3b2a43/windows/winpgnt.c#L1486

This line can't be correct. `SaveCertListOn` is set to 1 or 0 based on the string in `argv[i]` is `"-savelist"` or not, but this code branch is only entered if `argv[i]` is either `"-savecertlist"` or `"-savcecertlistoff"`. The second argument to `strcmp` should be `"-savecertlist"`.

**Comment by NoMoreFood** [comment]
Right you are.  I'll fix it up.

**Comment by NoMoreFood** [comment]
Just committed to the master branch.  If you wouldn't mind testing it out, I would appreciate it.

**Comment by jmyreen** [comment]
The `-savecertlist` and `-savecertlistoff` options work as expected after the change, setting the `SaveCertListEnabled` registry entry to `1` and `0`, respectively. Thanks.
