### ISSUE TITLE
PuTTY CAC version 0.73 Update 1 does not start on Windows 10

### ISSUE THREAD

**Issue by jmyreen** [NoMoreFood/putty-cac#51]
I have tried to run version 0.73 Update 1 (64-bit) on two Windows 10 (1909) machines, with the same result: PuTTY does not start. The busy cursor flashes for a brief moment, and then nothing. PuTTY.exe crashes, Pageant.exe works. I haven't tried the other programs.

I compiled the latest version from GitHub on Mingw-w64, and all went smoothly: the program ran without issue, except for one thing: the "Certificate" entry in the settings was missing. It was as if I had compiled the standard PuTTY. Is there some build configuration setting I missed, or is it not possible to compile the "cac" version with Mingw? Anyway, the startup problem could not be reproduced with the Mingw compiled version.

The following error is reported in the event log:

```
Faulting application name: putty.exe, version: 0.73.0.1, time stamp: 0x5e52e5e3
Faulting module name: putty.exe, version: 0.73.0.1, time stamp: 0x5e52e5e3
Exception code: 0xc0000005
Fault offset: 0x000000000002afb6
Faulting process id: 0x6b44
Faulting application start time: 0x01d5ed78d7a941e6
Faulting application path: C:\Program Files\PuTTY\putty.exe
Faulting module path: C:\Program Files\PuTTY\putty.exe
Report Id: 5a40248f-1bc0-4e6a-9ada-d80932a39c17
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by donovan-middleton** [comment]
Having same error on Windows Server 2012 R2.

**Comment by NoMoreFood** [comment]
Problem confirmed for the 64-bit version.  32-bit version works fine.  Weird; something must have been mucked up in the release process.  Will investigate and get back to you in the next few hours.  Thanks!

**Comment by NoMoreFood** [comment]
@jmyreen @donovan-middleton Can you try the rebuilt binaries I just posted?  In terms of building outside of Visual Studio, you probably need to define PUTTY_CAC pre-processor definition.

**Comment by jmyreen** [comment]
This version starts up. I'm using it right now, and no problems so far. Thanks!

**Comment by jmyreen** [comment]
The startup problem is fixed, probably also on Windows Server 2012 R2. If not, then that's some other problem. Closing.

**Comment by donovan-middleton** [comment]
It did work on Windows Server 2012 R2...  We just tested today.
