### ISSUE TITLE
"Remember Certs" and "Force PIN Caching" issues

### ISSUE THREAD

**Issue by darkain** [NoMoreFood/putty-cac#52]
1) If both "Remember Certs" and "Force PIN Caching" are disabled, when attempting to enable "Remember Certs", "Force PIN Caching" is also automatically enabled.

2) If "Remember Certs" is enabled, enabling/disabling "Force PIN Caching" works as expected.

3) If "Force PIN Caching" is enabled and "Remember Certs" is disabled, its impossible to enable "Remember Certs" without first disabling "Force PIN Caching" (which then as point 1, will enable both)

**Comment by NoMoreFood** [comment]
I will look into this.  Thank you for reporting it.

**Comment by darkain** [comment]
Seems great now. Thanks for the super fast turnaround time!
