### ISSUE TITLE
PuTTY CAC 0.73.0.2 failing on 64-bit systems

### ISSUE THREAD

**Issue by donovan-middleton** [NoMoreFood/putty-cac#53]
On my Windows 10 64-bit system, attempting to start PuTTY fails. A window does not appear and I do not see any tasks in Task Manager.
On Windows Server 2012 R2, I do see a crash message that I have attached.
Uninstalling and reverting back to PuTTY CAC 0.73.0.1 works fine.
![2020-04-02_8-10-05](https://user-images.githubusercontent.com/45984475/78254153-1a780100-74bb-11ea-9745-b6e0ffaabedb.png)

**Comment by NoMoreFood** [comment]
Lovely.  Probably another compiler optimization issue --  I've been consulting with Microsoft on fixing them -- supposed to be in the next release.  Can you see if 32-bit works okay?  I can address later today.

**Comment by donovan-middleton** [comment]
I only have 64-bit systems to test on, but the 32-bit version of PuTTY CAC 0.73.0.2 seems to be fine on the 64-bit platform. Only having issues with the 64-bit version of PuTTY CAC 0.73.0.2!

**Comment by NoMoreFood** [comment]
@donovan-middleton Can you please try the latest binaries?  It was the same compiler issue that caused a fault in the initial 0.73u1 build -- the compiler flag causing the issue snuck back in the project file.

**Comment by donovan-middleton** [comment]
It works again!
Also noticed that when you recompiled it again, the size for the 64-bit MSI decreased like it did last time.
Thanks again!

**Comment by NoMoreFood** [comment]
@donovan-middleton Yeah, the compiler bug relates to inlining of code.  Basically the setting tells the compiler to try to merge *any* functions together that it thinks will help performance.  This usually results in larger but faster code.  Microsoft has a fix in the works for the next Visual Studio 2019 update.
