### ISSUE TITLE
RFE: skip revoked certs

### ISSUE THREAD

**Issue by jamescassell** [NoMoreFood/putty-cac#54]
#32 introduced an option to skip expired certificates.  Would be helpful to have that same option also skip revoked certs.  This can be achieved on windows using:

Something like this command will do such filtering:
`Get-ChildItem -Eku "Smart Card Logon" -Recurse -path Cert:\CurrentUser\My\ | Where-Object { ($_ | Test-Certificate -ErrorAction SilentlyContinue -WarningAction SilentlyContinue) -ne 0}`

**Comment by NoMoreFood** [comment]
I will look into it.  Unfortunately in the world of C/C++ doing that test is slightly more involved than with PowerShell.  What do you think about potentially merging it all as one option?

**Comment by jamescassell** [comment]
I expect that would work just great. Not sure if other folks are using Smart Cards with certificates not trusted by their workstation, nor how the windows interface treats such certs with this function.

**Comment by NoMoreFood** [comment]
@jamescassell Sorry for the very late follow-up on this.  I've added a new filter in the latest build that should address this.  Please try it out: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by jamescassell** [comment]
Awesome! Will check it out.

**Comment by NoMoreFood** [comment]
Gonna closed this as released.  Re-open if you see any issues with it.
