### ISSUE TITLE
Add support for rsa-sha2-256/rsa-sha2-512

### ISSUE THREAD

**Issue by N6UDP** [NoMoreFood/putty-cac#55]
Today you get warnings using openssh clients >7.7 such as:
```
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
```
I believe I mostly figured out what needs to be done to add support:
1. Update calls to cert_capi_sign/cert_pkcs_sign/cert_sign to pass the flags through such as [here](https://github.com/NoMoreFood/putty-cac/blob/e63afd9bb95fb8616bf30e8e7836d45ccd484fcb/code/pageant.c#L366-L375) (and in the other places cert_sign is called)
1. Update cert_capi_sign/cert_pkcs_sign to support rsa-sha2-256/rsa-sha2-512 similar to the way support was added upstream for non-certs [here](https://git.tartarus.org/?p=simon/putty.git;a=commitdiff;h=13b29008b40249ded5af594b8c93ffb99d79b316) over [here](https://github.com/NoMoreFood/putty-cac/blob/master/code/cert/cert_capi.c#L68-L113)

I could try to put together a PR for the above but I don't actually have a pkcs library to test with so I'd really only be able to test cert_sign/cert_capi_sign.. although I do vaguely recall some generic CAPI PKCS library... 

Let me know if you want me to take a stab at it / think it would be easy enough to add.
Thanks,
Lee

**Comment by N6UDP** [comment]
Forgot to mention this is related to the closed #30, but upstream support was added in .71 :)

**Comment by NoMoreFood** [comment]
By all means take a stab at it.  Worst case is I may have to rework it just to fit my style since I have to be able to maintain it long term.  PKCS be a challenge since it’s very possible there haven’t been many libraries updated to support it.  It’s fine to focus on CAPI to start.  We’ll also have to be sensitive from a usage perspective that sha1 will still be the de facto standard for sometime to come.

**Comment by NoMoreFood** [comment]
@N6UDP I accepted your pull and am building on it (along with the PuTTY 0.74 changes that were just released).  I actually didn't realize it but PuTTY doesn't seem to support signing with rsa-sha2-512/rsa-sha2-256; only Pageant does.  What OpenSSH distributions are you using?

**Comment by N6UDP** [comment]
I use a number of OpenSSH distributions and tested with most/all of them: Ubuntu 18.04/20.04's builds on WSL1&2, the Windows native builds that ship inside of Windows across a few Windows 10 versions, and some cygwin/msys2 builds (like git bash) although much more rarely.  The version spread appears to be 7.7p1 -> 8.2p1.  I use https://github.com/benpye/wsl-ssh-pageant to bridge the ssh-agent -> pageant gap.
I have a few tokens available: a few yubikeys (various version that support CCID), some Gemalto .NET smartcards, and windows virtual smartcards / hello pin.

**Comment by N6UDP** [comment]
Looks like you already took care of `cert_get_hash` changes I mentioned the PR in [this](https://github.com/NoMoreFood/putty-cac/commit/2d9c8af239c32266ca9499353c832b4084a98dbd) commit.. I was about to take a stab at it and reset to master to find it was done :) 👍 
I've tested your 0.74 build with the native and WSL OpenSSH and it works.
