### ISSUE TITLE
Reimplement support for pkcs11 auth (like nitrokey hsm2)

### ISSUE THREAD

**Issue by mcmufffin** [NoMoreFood/putty-cac#58]
Hi There,

i just got my hands on a nitrokey hsm 2 and im trying to get it to work with putty-cac, unfortunately it seems like support for pkcs11 auth was removed with the fork, just cert based pkcs11 seem to be left

Are there any plans to reimplement using straight keys like in putty sc? 

thanks!

regards

**Comment by NoMoreFood** [comment]
If you referring to exercising a public key / private key container set without a corresponding certificate container, then I do not have plans to implement it.  We don't have many PKCS 11 users the way it is and certificates are closely bound to how the CAPI/PKCS abstraction layer is designed.  I'd recommend just creating a self-signed certificate and adding it in order for PuTTY CAC to locate and use the keypair.

**Comment by mcmufffin** [comment]
Hi,

thanks for the tipp! I tried that yesterday but since i tried just public / prive key pair containers first, i checked "skip smartcard certs". After switching to a cert based setup i totally forgot that i check the box and the certs were skipped 🥇 

Works now :)

regards
