### ISSUE TITLE
Pageant only lists certificates that don't have extended usage attributes

### ISSUE THREAD

**Issue by MTres19** [NoMoreFood/putty-cac#59]
I am using OpenSSL to generate self-signed certificates and then loading them onto my PIV card. To help differentiate between the four different key slots when using the card, I added extended key usages to the X.509 certs such as "encrypted email," "code signing," and "Microsoft encrypted file system" as described in the [OpenSSL manual page](https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html).

Since I didn't mark the extended key usage field as a critical field, it seems that Pageant should list all the qualifying certs, but I found that only the certificate that I had not assigned an extended key usage was shown when I selected "Add CAPI cert" from the Pageant context menu.

This isn't a major issue—I'll just label the keys differently in the subject attribute and remove the extended key usage attribute—but I thought I should mention it.

**Comment by NoMoreFood** [comment]
Hmmm... we may have a bug in this part of the certificate selection based on a quick glance at the code.  Does the behavior change when you select the 'Filter Smart Card Logon Certs' in checked in Pageant?

**Comment by NoMoreFood** [comment]
Closing due to no response.  The filtering logic was modified in the last build so maybe see if that better aligns with your needs and reopen this if necessary.
