### ISSUE TITLE
Question: Load specific CAPI certs when pagent starts

### ISSUE THREAD

**Issue by JuddTracy-DAS** [NoMoreFood/putty-cac#62]
So I want to be able to load certain CAPI certs from the command line when launching pagent but don't know if that is possible?

My issue is that when I have all of the my certs load from CAPI some ssh sessions will fail with trying too many authentication request.  I only really need two loaded up but I haven't figured out how the do that from the command line so I don't have to manually configured pagent every time.

**Comment by NoMoreFood** [comment]
Assuming that the certificate is your certificate store, all you have to do is run pageant.exe CAPI:thumbprint (e.g., pageant.exe CAPI:fbe6e56631036ef34162bcfc1c259a32ff2f046c)

**Comment by JuddTracy-DAS** [comment]
Thanks, I don't know why I didn't try that but it does work for what I want.  Is that documented anywhere incase other users need it?

**Comment by NoMoreFood** [comment]
Only in previous issues/questions: https://github.com/NoMoreFood/putty-cac/issues/13.  At some point, I'll get around to documenting all the various switches.
