### ISSUE TITLE
Pageant 0.75 crashes when loading a .ppk key

### ISSUE THREAD

**Issue by grawity** [NoMoreFood/putty-cac#64]
While Pageant-CAC seems to work fine with CAPI keys, it crashes every time I try to load a key from a .ppk file (whether RSA or EdDSA, with passphrase or without, old or new PPK format).

PuTTYgen-CAC does not have this issue, and neither does upstream Pageant 0.75.

**Comment by NoMoreFood** [comment]
I see the problem.  Will have a version for you to test tomorrow night.

**Comment by NoMoreFood** [comment]
@grawity Please see if these binaries address your issue: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by grawity** [comment]
Thanks, tested; it seems to be working fine.

**Comment by NoMoreFood** [comment]
Released as PuTTY CAC 0.75u1.  Thanks for reporting and testing.

**Comment by chuckmilam** [comment]
Just hit this myself, new binaries solved the issue.
