### ISSUE TITLE
ignoring EKU when using cert from Windows Certificate Store

### ISSUE THREAD

**Issue by henning-schild** [NoMoreFood/putty-cac#65]
Is there a way to ignore the Key Usage and Extended Key Usage and use keys meant for "something else".

I do have a token with a key meant for "Encryption", on Linux with ssh i can use it as long as the server allows that key. On Windows with putty-cac i can not choose that "wrong" key even though the server would accept it.

I am not sure if "Key Usage" and "EKU" are not more than a "hint" to the user of a key. I have seen applications warning me about "incorrect key usage" but generally allowing me to "pick the wrong key" given "i know what i am doing". So i think it would be nice to have a checkbox "Ignore Key Usage" giving people access to keys where the eku might not fit.

**Comment by NoMoreFood** [comment]
I will consider this in a future release.

**Comment by henning-schild** [comment]
In fact not just ExtendedKeyUsage but also KeyUsage need an optional filter, i managed to write a pretty messy patch and compile myself. Not sure i should share that patch somehow, but when putty-cac ignores the keyusage my use-case works.

**Comment by NoMoreFood** [comment]
I added -allowanycert and -allowanycertoff command line arguments to Pageant to make any certificate selectable.  These only have to be ran once as they toggle the registry key HKCU\SOFTWARE\SimonTatham\PuTTY\AllowAnyCert.  I am not going to add this so GUI since this is not behavior I think we should be generally encouraging. 

If you're interesting in test, you can try the binaries here:

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by henning-schild** [comment]
I can confirm that the pageant.exe does the trick. Not too sure about the way you decided to expose it while hiding it at the same time. I agree it should maybe not be in the GUI but is there any mention in any kind of documentation?

I looked at the commit but it is very much non atomic and seems to be doing multiple things. I think it is 401fb359043bdaf4759d09b51cb0bb4c3a717f6d and from what i can tell it is really "hidden".

Cool that it works and is already in "master", but say i wanted to use that in a year from today ... even i would have a hard time finding how to do so. And you would as well. So i think it might deserve some sort of "hidden documentation". A GUI is kind of documentation, so if there is an expert/advanced/danger tab ... it could sit there. Or maybe in the README ... at least a place where people can find it when looking for it, without reading code.

**Comment by NoMoreFood** [comment]
Thank you for testing. I agree we need more documentation; it would be nice is somebody could provide more thorough documentation; this doesn't have to be a one man show ;-).  Can you open a separate issue to solicit documentation on the command line options and we'll concentrate on it in that thread?

**Comment by henning-schild** [comment]
I see, if putty itself has cmdline options but no docs for that, it is indeed a more generic problem. Personally i am not using Windows nor Putty-CAC. So i would not be the right person for that job i am afraid.

I think this one can be closed. There is a way get use the certs, it is just hard to find ... which as you said is maybe another issue. But i will not close it, you might have had a reason to keep it open.
