### ISSUE TITLE
generate Makefiles like putty does

### ISSUE THREAD

**Issue by henning-schild** [NoMoreFood/putty-cac#66]
i wanted to recompile on a Linux host using `code/windows/Makefile.mgw`, while that did compile it was missing the actual bits ... which seem to be only available when using VS2019

A better approach to this repo would probably be "forking putty", and adding patches on top. And making sure the build systems supported by putty itself remain working. And in case VS2019 is missing in putty, maybe contributing that upstream. That way it would be clear what was added/changed and all build systems supported by putty would remain working.

**Comment by NoMoreFood** [comment]
While the PKCS library code should technically work in Linux, the libraries and headers to support CAPI would not without something like MinGW (which I'm not sure even has _all_ those calls).  How did you get it to compile?

**Comment by henning-schild** [comment]
On a debian 
```
apt-get install mingw-w64
cd code/windows
export TOOLPATH="i686-w64-mingw32-"
make -f Makefile.mgw
```

The idea was to compile for Windows ... just without having a toolchain on the target. While that did produce working binaries ... those were lacking the actual cac.

**Comment by NoMoreFood** [comment]
Ok.  So, to clarify, what you're requesting is that the makefiles include references to the preprocessor definitions, include paths, and source files necessary to compile the code on Linux?

**Comment by henning-schild** [comment]
Yes, if somehow possible it would be nice to compile putty-cac (for Windows) on Linux. A good first step would probably be to modify "Recipe" and generate the Windows-Build-Instructions with "mkfiles.pl". I started that but stopped when i ran into missing headers.

It would also enable the use of github actions for CI

**Comment by NoMoreFood** [comment]
It appears the upstream pre-release (0.77) has moved to makefiles.  It's been migrated over to PuTTY CAC here:

https://github.com/NoMoreFood/putty-cac/tree/fido_dev_branch
