### ISSUE TITLE
Feature request: Auto Remove Keys Once the card/token is Removed 

### ISSUE THREAD

**Issue by eldadh** [NoMoreFood/putty-cac#67]
I would like to know it it is possible for the agent to auto load keys from PKSC smart card load the key from the card only when inserted and then only to memory,
and once the hardware key is removed the agent will forget/remove the key. 
in order to avoid tailgating / abuse.

Thnx for great software
eldadh

**Comment by NoMoreFood** [comment]
This wouldn't be an easy change, but potentially possible.  However, only than cleanliness, I don't see much value in this.  Without token inserted, you neither have the private key nor the PIN used to access it.  Can you elaborate on how this "tailgating / abuse" might occur?

**Comment by NoMoreFood** [comment]
Closing due to lack of response / activity.
