### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by JinZhuXing** [NoMoreFood/putty-cac#68]
Is there any similar project for Linux?
I need to use putty-cac at Linux.
Please help me.
Thank you.

**Comment by henning-schild** [comment]
On Linux all you need is OpenSC.

Then you list the keys on your "token" like so

```
ssh-keygen -D /usr/lib64/opensc-pkcs11.so -e
```

to use it for ssh

```
ssh -I /usr/lib64/opensc-pkcs11.so ...
```

or `PKCS11Provider /usr/lib64/opensc-pkcs11.so` in `~/.ssh/config`

The path of the library will vary depending on your distro.

**Comment by JinZhuXing** [comment]
Thank you very much.
