### ISSUE TITLE
pageant crashes on "copy to clipboard" of encrypted Keys

### ISSUE THREAD

**Issue by donestefan** [NoMoreFood/putty-cac#70]
After adding encrypted keys, a simple double click on the key will cause pageant to crash. The same when clicking on "Copy to clipboard" button.
`pageant.exe" --encrypted "C:\Users\xxx\my-putty-key.ppk`
On decrypted keys everything works fine.

Release 0.75-1 on Win10 20H2

**Comment by NoMoreFood** [comment]
Thanks for reporting. I believe I've identified the issue and will release a fix soon.

**Comment by NoMoreFood** [comment]
Can you verify the latest build resolves this issue for you:

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by donestefan** [comment]
I can confirm, that the problem is gone in version 0.75u2 👍 
Thanks a lot for the fast reply!
