### ISSUE TITLE
[feature request] Key Auth Prompting

### ISSUE THREAD

**Issue by donestefan** [NoMoreFood/putty-cac#71]
Would you mind expanding the existing "cert auth prompting" feature to regular non-cert keys? 
It would be much appreciated!

**Comment by NoMoreFood** [comment]
I reviewed the spots where adding this functionality would be necessary and it would complicate maintainability of the PuTTY CAC code relative to upstream changes.  I recommend making a suggestion to the upstream PuTTY project.
