### ISSUE TITLE
PuTTY PKCS signing problem on Windows 10

### ISSUE THREAD

**Issue by andrew-min** [NoMoreFood/putty-cac#72]
Hi, I have a strange problem. pkcs library is loaded to pageant, agent forwarding is on. my steps are:

- open ssh session via putty (pin + yubikey touch)
- open ssh session via commad sss -A host (yubikey pin request window appears)
![image](https://user-images.githubusercontent.com/54099714/124075940-42ec0380-da4e-11eb-909b-b1f5bda8dde8.png)
- enter pin (it's accepted)
 ![image](https://user-images.githubusercontent.com/54099714/124075600-c6592500-da4d-11eb-82cf-213a4798c84c.png)

some second later i get
![image](https://user-images.githubusercontent.com/54099714/124076030-61ea9580-da4e-11eb-9d1a-151adf287e7f.png)

I've tried both 32 and 64 bits versions, same result

**Comment by NoMoreFood** [comment]
Which version of PuTTY CAC?  Has any version ever worked?  Is it only in an agent forwarding scenario?

**Comment by andrew-min** [comment]
Hi. I've started from 0.75 and have not tried older versions of putty cac
![image](https://user-images.githubusercontent.com/54099714/124240694-a85df400-db23-11eb-97b3-aa6bc32c95d6.png)

agentf forwarding scenario is the only I have to use, I have two jump-hosts before certificate from pageant is used.
the output of ssh-add -L  is ok on the last jump-host.

**Comment by NoMoreFood** [comment]
Can you provide details on which version of OpenSC you're using and what signing algorithm / strength?

**Comment by andrew-min** [comment]
I have tried OpenSC 0.21.0, 0.22.0-rc1 both 32 and 64 bits versions.
about signing algorithm / strength i can say nothing. Where can i look up this information?

**Comment by NoMoreFood** [comment]
It should recorded in the certificate you are using.  If you can attach your certificate, that would be helpful.

**Comment by andrew-min** [comment]
signing algorithm is sha256RSA, public key RSA (2048 bits)

**Comment by andrew-min** [comment]
Sorry, i think this is a  problem of access rights.
