### ISSUE TITLE
Unable to detect CAPI certificate

### ISSUE THREAD

**Issue by kitma-gmail** [NoMoreFood/putty-cac#76]
Not sure if this is the right place to post.
I have installed putty-cac 0.76 64-bit on Windows server 2016 and tried to authenticate certificate from Yubikey already inserted. I go to Connection > SSH > Certificate and click on "Set CAPI Cert", it gives me the message that no certificate could be found. I'm quite sure that Windows machine can detect Yubikey and the browser can detect this Yubikey in order to connected to secured site. Only putty could not detect it. Any suggestion?

**Comment by NoMoreFood** [comment]
The Yubikey forums may be more appropriate.  Do you have an appropriate Smart Card minidriver installed (e.g., https://www.yubico.com/support/download/smart-card-drivers-tools/) and have you generated a certificate and put it on your Yubikey?

**Comment by kitma-gmail** [comment]
Yes, the Yubikey has been registered and it is working well with other app (Chrome) on the same machine. I can also get putty work with Yubikey on Windows 10. Therefore, I suspect that it could be an issue with the use of putty-cac/Yubikey in Windows server 2016. I have also submitted a support ticket to Yubico support.

**Comment by NoMoreFood** [comment]
In terms of certificate selection dialog, PuTTY CAC is just reading the Windows certificate store and presenting the user a list of eligible certs.  At that point, the hardware token itself is not in the picture.  There is some filtering enabled to ensure it looks like a good certificate for authentication.  Attach the certificate you're using here or email it to me and I can tell you if it looks good.

**Comment by kitma-gmail** [comment]
Thank you for the information. I search for Yubikey certificate in the Windows certificate store manager but it is not there. It is not Puttty-CAC issue. There is issue with Yubikey and I submitted a ticket to Yubico. Thank you very much for the help.
