### ISSUE TITLE
problem with pageant of Putty-CAC, don't remember the PKCS file

### ISSUE THREAD

**Issue by Quarantainenet-ITservices** [NoMoreFood/putty-cac#78]
Hello,

Some of our users are having a problem with pageant of Putty-CAC.
If they add the PKCS file 'opensc-pkcs11.dll' to the 'Pageant Key List' and then tick 'Remember Certs' and then reboot the laptop or close pageant with Exit. When they start pageant again, the PKCS file is not saved in pageant, you have to add it manually and the 'Remember Certs' is still checked.

Do you have a solution for this problem?

**Comment by NoMoreFood** [comment]
Problem reproduced.  The loading works of remembered certs looks fine, but not the saving.  Will released updated binary tonight.

**Comment by NoMoreFood** [comment]
@Quarantainenet-ITservices  Can you verify these updates binaries address your issue: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by Quarantainenet-ITservices** [comment]
I sent the binary link to a colleague and he installed pageant on his laptop and the problem was solved, Thanks for the fix.
