### ISSUE TITLE
Resource IDs should have constants

### ISSUE THREAD

**Issue by GigabyteProductions** [NoMoreFood/putty-cac#8]
Example: https://github.com/NoMoreFood/putty-cac/commit/e41c556ba6348d251dbe139773082115c0d250ae#commitcomment-23300358

While it may be moot in cases like https://github.com/NoMoreFood/putty-cac/blob/master/windows/winpgnt.c#L607, it is notable that the ID meanings are sometimes mixed up (see: https://github.com/NoMoreFood/putty-cac/blob/master/windows/pageant.rc#L37).

Solution: Constants for IDs defined in a header; both source modules and resource files should include those headers and use those contants for the IDs.

**Comment by NoMoreFood** [comment]
Agree with your comment, generally speaking.  If I had any control of the upstream code (PuTTY), I would definitely change it.  And like 100 other things -- I'm definitely not a fan of the PuTTY codebase (e.g., terrible indenting, lots of correctable warnings in Visual Studio).  Being that I don't have control of upstream code, I try to follow the axiom of only making delta changes in the code style / technique of the original file even if those aren't best practices.  While it may introduce room for error as you indicated, so does making larger changes to sections of code we'll have to try to merge later.  If you can convince the maintainers of PuTTY to make the corresponding changes in the upstream first, PuTTY CAC will gladly adapt. 

The only thing I see wrong in the second link is the comment next to the case statement -- which I will fix.  Please let me know if you see something else.

**Comment by GigabyteProductions** [comment]
I suspected that you were just trying to stick with what upstream does, but applying best practice to _new_ code is also doable here ("Add PKCS Cert", "Add CAPI Cert", and their IDs are "new" to upstream Putty).

Regarding the second link: Yes; I was referring to the comments. I do understand there is no functional difference between the comment or case order, but I thought it was at least notable. That kind of thing has potential to cause issues in development, because of people of applying their code around what the comment says and nobody noticing it's wrong.

**Comment by NoMoreFood** [comment]
Address in latest commit (https://github.com/NoMoreFood/putty-cac/commit/5f74bce8b0c79035f8b4e1cdd48386b87ec0a036).
