### ISSUE TITLE
Server refused public-key... with imported cert into windows keystore

### ISSUE THREAD

**Issue by sharkydog** [NoMoreFood/putty-cac#80]
Using certificate from a smart card (yubikey 5) work fine.
When I import the cert (and pkey) as PFX into keystore, I get:
> Server refused public-key signature despite accepting key!

Tried with different (new) cert and with the one on the Yubi.

The PFX was exported with:
> openssl pkcs12 -export -in ssh.crt -inkey ssh.key -out ssh.pfx

Both smart card and imported cert work in Firefox https client auth and OpenVPN GUI.

sshd says:
mm_answer_keyverify: publickey 0x55557f457510 signature unverified: invalid argument

**Comment by sharkydog** [comment]
FileZilla SFTP works with the certificate (from pageant), but not PuTTY.

**Comment by NoMoreFood** [comment]
What is the version of the backend SSH server you are connecting to?  Does authenticating from PuTTY (without Pageant running) produce the same results?

**Comment by sharkydog** [comment]
sshd - OpenSSH_8.4p1 Debian-3, OpenSSL 1.1.1i  8 Dec 2020

PuTTY 0.74 is the last to work, all above fail, upstream and yours, agent and no agent.

**Comment by sharkydog** [comment]
I may have another pointer.
When I load the cert (smart card or imported) into pageant, and I select "Cert Auth Prompting", then after I choose "No" when asked, I get the same error.
That is on PuTTY 0.73, both certs work if I accept the prompt.

**Comment by sharkydog** [comment]
Okay... so looks to be NOT an issue with PuTTY.

> openssl pkcs12 -export -in ssh.crt -inkey ssh.key -out ssh.pfx -CSP "Microsoft Enhanced RSA and AES Cryptographic Provider"

This fixed it, without -CSP option, key was imported in "Microsoft Enhanced Cryptographic Provider v1.0" which apparently does not play with SHA-2

**Comment by sharkydog** [comment]
Probably related to #77

**Comment by MetricMike** [comment]
Yup, same issue as #77.

As a possible fix, putty-cac could try to detect which CSP the specified key is using and either display a warning or attempt sending a SHA1 sig?

**Comment by NoMoreFood** [comment]
@MetricMike I think we could possibly force it to use SHA1 using a registry key regardless if the remote host supports SHA2.  Is there something wrong with the fix that @sharkydog suggested?  Servers will stop supporting SHA1 at some point...

**Comment by NoMoreFood** [comment]
Just got around to rebuilding my development environment so I'll be taking a look at this over the next few weeks while on leave.  It would be great to have some testers lined up if anyone is interested.

**Comment by MetricMike** [comment]
Happy to test!

**Comment by NoMoreFood** [comment]
@MetricMike I uploaded a new version to https://github.com/NoMoreFood/putty-cac/tree/master/binaries.  Can you give it a try?  New behavior should be to use SHA512/SHA256 only if the legacy CSP supports it.

@sharkydog If you want to test, feel free.

**Comment by sharkydog** [comment]
Doesn't work, same error, putty 0.73 works, pageant version doesn't matter.

But, I saw one difference between 0.76-1 and 0.76-2.
When I import the pfx cert and enable "strong key protection" so I am prompted (by windows) every time the key is used, with 0.76-2 I see the prompt and then the error, with 0.76-1 it goes straight to the error.

**Comment by sharkydog** [comment]
I created two so they can be both imported
[ssh_test.zip](https://github.com/NoMoreFood/putty-cac/files/7757444/ssh_test.zip)

ssh_test_csp.pfx is set with "Microsoft Software Key Storage Provider", ssh_test_nocsp.pfx has no CSP option set.
pub files are for authorized_keys

**Comment by NoMoreFood** [comment]
Weird.  I cannot reproduce the 'nocsp' failure on the latest development version - it successfully downgrades to SHA1 signatures when the CSP doesn't support it.  I can reproduce the failure on the 0.76u1 released version (as expected).  Could I get a copy of our sshd_config file on the server? Or any other ideas what might be different between us?

**Comment by sharkydog** [comment]
[sshd_config.txt](https://github.com/NoMoreFood/putty-cac/files/7757964/sshd_config.txt)
OpenSSH_8.4p1 Debian-3, OpenSSL 1.1.1i  8 Dec 2020

Maybe default CSP is different in your machine?
Mine nocsp was imported in "Microsoft Enhanced Cryptographic Provider v1.0"
certutil -user -store my 25f536a7e285dbe1611bbba9f3bdd34ff4375d37

**Comment by sharkydog** [comment]
And putty log after this:
> Event Log: Offer of public key accepted
> Event Log: Sent public key signature
> Outgoing packet #0x6, type 50 / 0x32 (SSH2_MSG_USERAUTH_REQUEST)

073-2
>   00000000  00 00 00 09 73 68 61 72 6b 79 64 6f 67 00 00 00  ....sharkydog...
>   00000010  0e 73 73 68 2d 63 6f 6e 6e 65 63 74 69 6f 6e 00  .ssh-connection.
>   00000020  00 00 09 70 75 62 6c 69 63 6b 65 79 01 00 00 00  ...publickey....
>   00000030  07 73 73 68 2d 72 73 61 00 00 01 17 00 00 00 07  .ssh-rsa........
>   00000040  73 73 68 2d 72 73 61 00 00 00 03 01 00 01 00 00  ssh-rsa.........

076-2
>   00000000  00 00 00 09 73 68 61 72 6b 79 64 6f 67 00 00 00  ....sharkydog...
>   00000010  0e 73 73 68 2d 63 6f 6e 6e 65 63 74 69 6f 6e 00  .ssh-connection.
>   00000020  00 00 09 70 75 62 6c 69 63 6b 65 79 01 00 00 00  ...publickey....
>   00000030  0c 72 73 61 2d 73 68 61 32 2d 35 31 32 00 00 01  .rsa-sha2-512...
>   00000040  17 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 03  .....ssh-rsa....

**Comment by NoMoreFood** [comment]
That's helpful.  PuTTY adds that initial "rsa-sha2-512" in another spot that I hadn't accounted for and apparently your server is pickier it about it than mine is.  More to come...

**Comment by NoMoreFood** [comment]
@sharkydog New version uploaded.  Can you try again?

**Comment by sharkydog** [comment]
This one works.
But if pageant is loaded and the nocsp cert is in, putty failed with the cert from pageant and then fails again with the same cert from session.

**Comment by NoMoreFood** [comment]
@sharkydog I think we are getting closer. Just pushed a new version; please give it a try.

**Comment by sharkydog** [comment]
with csp cert in both agent and session, putty first tries agent and fails then tries session and succeeds.
difference in signature packet start at these lines
agent
>   00000150  77 16 cc e4 7f 60 b3 dd 00 00 01 0f 00 00 00 07  w....`..........
>   00000160  73 73 68 2d 72 73 61 00 00 01 00 7f f4 a8 77 75  ssh-rsa.......wu
session
>   00000150  77 16 cc e4 7f 60 b3 dd 00 00 01 14 00 00 00 0c  w....`..........
>   00000160  72 73 61 2d 73 68 61 32 2d 35 31 32 00 00 01 00  rsa-sha2-512....

with nocsp cert both fail, session packet is much shorter, diff at
agent
>   00000030  0c 72 73 61 2d 73 68 61 32 2d 35 31 32 00 00 01  .rsa-sha2-512...
>   00000040  17 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 03  .....ssh-rsa....
session
>   00000030  07 73 73 68 2d 72 73 61 00 00 01 17 00 00 00 07  .ssh-rsa........
>   00000040  73 73 68 2d 72 73 61 00 00 00 03 01 00 01 00 00  ssh-rsa.........
[putty-csp.log](https://github.com/NoMoreFood/putty-cac/files/7760277/putty-csp.log)
[putty-nocsp.log](https://github.com/NoMoreFood/putty-cac/files/7760278/putty-nocsp.log)

Works without agent.

**Comment by NoMoreFood** [comment]
Thank you, that was helped.  I found two spots that I needed to be updated.  Can you try again and see if there is any improvement?

Note that the reference to 'ssh-rsa' at 0x00000040 is expected for any RSA usage if I am to believe that the upstream PuTTY code is following the rules.

**Comment by NoMoreFood** [comment]
@sharkydog Thank you, that was helped. I found two spots that I needed to be updated. Can you try again and see if there is any improvement?

Note that the reference to 'ssh-rsa' at 0x00000040 is expected for any RSA usage if I am to believe that the upstream PuTTY code is following the rules.

**Comment by sharkydog** [comment]
csp cert from agent now works, nocsp still does not
[putty.log](https://github.com/NoMoreFood/putty-cac/files/7762916/putty.log)
.

**Comment by NoMoreFood** [comment]
New version posted.  Can you try again and see if there is any improvement?

**Comment by sharkydog** [comment]
This is getting weird, now it works with nocsp from agent, but if the same cert is also in session, log says cert is being used from agent.
If session has different cert, that takes over and works
[putty_nocsp_agent.log](https://github.com/NoMoreFood/putty-cac/files/7763350/putty_nocsp_agent.log)
[putty_nocsp_agent_session.log](https://github.com/NoMoreFood/putty-cac/files/7763351/putty_nocsp_agent_session.log)

**Comment by NoMoreFood** [comment]
Ok, I switched the hash detection to use the comment from the agent key instead of from PuTTY.  Since PuTTY didn't have one set in your test, it was just assuming it supported SHA-256.  New version posted.  Fingers crossed.

**Comment by sharkydog** [comment]
works, but ..... this time no but :)
As far as I can tell, it's ok.

**Comment by NoMoreFood** [comment]
@sharkydog Awesome. Your dedication and speed to help test is admirable and appreciated.  Thank you very much.

@MetricMike Curious on your input for this latest version.

**Comment by sharkydog** [comment]
Well, there is one but, filezilla with don't know which version of putty throws the error with nocsp cert from agent

**Comment by sharkydog** [comment]
Same with original putty (0.76) with cert from your agent, csp - ok, nocsp - no

**Comment by NoMoreFood** [comment]
Is Filezilla use PuTTY.exe or Pageant.exe?

**Comment by sharkydog** [comment]
newest version uses something based on putty - fzsftp.exe
They (and putty) are probably not expecting sha1 sigs

**Comment by NoMoreFood** [comment]
I'll take a look.

**Comment by NoMoreFood** [comment]
Alright.  I added another check to force a SHA-1 downgrade in Pageant to hopefully address that.  New version is out there.

**Comment by sharkydog** [comment]
I still get the error.

**Comment by sharkydog** [comment]
This time however I see the windows prompt for the super secure key and then the error, previous version - straight to the error

**Comment by NoMoreFood** [comment]
Interesting.  It's working for me using your No CSP key in the newer version of Pageant.  It wasn't before the change.  Hmmm

**Comment by sharkydog** [comment]
Nope, from pageant 0.72
filezilla and putty 0.76 fail with both certs,
latest putty cac (1h ago) work only with nocsp cert.

**Comment by sharkydog** [comment]
log from putty 0.76 trying nocsp cert from latest agent
[putty.log](https://github.com/NoMoreFood/putty-cac/files/7764683/putty.log)

**Comment by NoMoreFood** [comment]
Yeah, that's expected from 0.76 to 0.76u2 (due to a bug in 0.76).  Based on it not working on 0.72 (which would have unconditionally not known about SHA256/SHA512 sigs), I don't think there's anything we can do.  The FileZilla client is likely assuming the agent signature is signed with SHA2 and prepending that onto the response.   Might be as good as we can make it.

**Comment by sharkydog** [comment]
I'm fine with it, I would have been a problem if I haven't figured out the problem with my certificates in the first place.
The important thing to me is filezilla and sourcetree to use certificates on a smart card or windows keystore.
And they can, with your pageant and keys in sha2 capable CSP.
I participated in this topic because you asked :)

**Comment by MetricMike** [comment]
Success!

DefaultCSP (no SHA-2 support) fails in 0.76u1 with putty setting or loading from pageant. Same settings work with 0.76u2

Strong CSP (SHA-2 support) works in both 0.76u1 and 0.76u2.

Sorry for the delay, this will be a huge help :)

**Comment by sharkydog** [comment]
Then, if there is nothing to be done to force non putty-cac clients to send sha1 sigs from pageant, this can be closed :)
