### ISSUE TITLE
PIV support

### ISSUE THREAD

**Issue by JennyHoo** [NoMoreFood/putty-cac#81]
If a PIV is used for the first time, putty will automatically store the certs into the personal certificates storage. After that, putty will not require PIV any more, because the cert is always pulled from the personal certificates storage. Is it possible to now store the certificate locally, and always require presence of PIV card for public key authentication? This is a security concern: a person can walk away with his/her piv card removed, an imposter can try to connect with the saved cert.

**Comment by NoMoreFood** [comment]
The certificate is only half of the information required to authenticate. It contains the public key which, from an cryptography perspective, can remain on the machine indefinitely without any risk to the systems on which it used.  You can safely send your certificate to anyone in the world - and this is actually how basic email encryption works.  The sensitive part is called the private key and, in the case of a PIV, there is literally no way PuTTY CAC or any other password can extract or cache it.  You literally need it inserted in the card reader in order for it to be used for authentication.  of the On a PIV,

**Comment by JennyHoo** [comment]
Bryan,

Thanks a lot for you immediate response. I learn a lot from it. Have a wonderful weekend!

Jenny

**Comment by JennyHoo** [comment]
Thanks!
