### ISSUE TITLE
Suggestion: Pageant key usage confirmation for all keys

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#82]
Hi @NoMoreFood ,

This issue is based on #22. Sorry if I return to ask something you don't want to implement in the past. But, I need to explain my use-case:

- As admin I need to login to a lot of different systems. These systems can be accessed by password, keys and certificates. The Pageant-CAC it's from my point of view the best Key Agent Manager for Windows. It's robust and it's based on standard Pageant. However, the current "key usage confirmation" is annoying. When mixing keys and certificates only the last can be checked. And I can't run more than one Pageant. So if I need certificates _and_ keys, then I need to disable the usage confirmation. And that's a pain.

I remember that you want to maintain this fork very simple. And I gree with that. However, please note about the KiTTY Pageant commented initially: it implements the same confirmation for all keys. Futhermore with (optionally) a ballon message when any is used (very useful if you use the PIN cache).

So please, see the code of this another fork:
https://github.com/cyd01/KiTTY/blob/3f2c71a3f11bd2ed3df66cbecbd2981b3ef01b69/0.76_My_PuTTY/pageant.c#L846
https://github.com/cyd01/KiTTY/blob/3f2c71a3f11bd2ed3df66cbecbd2981b3ef01b69/0.76_My_PuTTY/pageant.c#L920

I checked you current code, and I feel it will very simple to insert something similar before:
https://github.com/NoMoreFood/putty-cac/blob/3bf3faf18fb5f71491eaef1b6bb6b35e31905d72/code/pageant.c#L772

That's the only required point where present a modal window to the user asking if s/he wants to use that key.

For sure, I can do it for myself (copying from the KiTTY fork, and inserting the code in your PuTTY-CAC) but I prefer if this functionality will be added standalone. So, for this reason I ask you with all respect.

Please comment on this suggestion; or close it if you reject it.
Anyway thank you for maintaining this great fork!
Regards.

**Comment by NoMoreFood** [comment]
I will consider this in a future release.

**Comment by NoMoreFood** [comment]
@lars18th Please test the version in https://github.com/NoMoreFood/putty-cac/tree/master/binaries.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> @lars18th Please test the version in https://github.com/NoMoreFood/putty-cac/tree/master/binaries.

Thank you! It seems to work. 👍 

However, I discovered a problem that I don't feel it's related to this enhancement. But with this new beta version (64bit binary) when I mix CAPI and PuTTY Keys, the Pageant crashes. For example, I load one of them. Then I use it. And if after that I load the other, the binary closes. This is true even if CAPI or PuTTY it's first loaded. But only _after_ the key is used. So if I load both, only after the first use the binary closes.

Hope you can fix this.
Regards.

**Comment by NoMoreFood** [comment]
@lars18th I believe I identified the source of the crash and will upload a fixed version later today.

**Comment by NoMoreFood** [comment]
@lars18th Can you try with the latest development files?

**Comment by lars18th** [comment]
> @lars18th Can you try with the latest development files?

I'll do when they be available. Last release is at time "PuTTY CAC 0.76 Update 1".

**Comment by NoMoreFood** [comment]
Posted at https://github.com/NoMoreFood/putty-cac/tree/master/binaries like before.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> Posted at https://github.com/NoMoreFood/putty-cac/tree/master/binaries like before.

It improves. Thank you! Now I can load a key, connect with it, after load another one (a certificate, for example), and connect with it. No problem here. This part of the bug seems fixed.

However, now after using a key and a certificate, if I remove the certificate and I'll try to connect (using the key), then in this point the pageant closes. So I suspect some other (related) bug continues inside.

I hope you can finally fix it.
Regards.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Two questions regarding this issue, but not related with the bug (for this reason I write it in another post):

- The current message is a confirmation window asking to use or refuse a key/certificate. This window appears when the option "Cert & Key Auth Prompting" is selected. That's right and thank you for including it. However, I lack the option to show a message when the key is used. Let me to explain: if the option is disabled, then the Pageant don't ask for a confirmation. But nothing indicates to the user that one key is used. I know that this is the default behaviour of the original Pageant. But IMHO it will be interesting that the user can see (with a ballon in the tray, for example) that one key is used. You want to implement this, please?
- Another point is to provide a general shortcut to enable/disable the Auth Prompting. By default I prefet to have it enabled. But for some connections using scripts, it will be necessary to disable it. So, I want a simple method to enable/disable on-the-fly using only the keyboard. What you think about this?

Regards.

**Comment by NoMoreFood** [comment]
For the first request - I familiar with how to do that, but not going consider it at the moment.  I'm not a big fan of how Windows handles shell notifications and there a bunch of timing parameters to prevent applications from "spamming" the user that cannot be easily subverted so it wouldn't be reliable without some extra work.

For the second request, I recommend just using your favorite mechanism to bind a shortkey (e.g. AutoHotkey) to one of the following commands: 

```
REG ADD "HKCU\Software\SimonTatham\PuTTY" /F /V "CertAuthPrompting" /T REG_DWORD /D 0
REG ADD "HKCU\Software\SimonTatham\PuTTY" /F /V "CertAuthPrompting" /T REG_DWORD /D 1
```

Or, alternatively, leverage the command line processor from of the PuTTY apps to toggle the keys indirectly:

```
plink.exe -certauthprompting -V
plink.exe -certauthpromptingoff -V
```

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> For the first request...

So, I hope you'll want to implement it at some point in the near future. 😉 

> For the second request...

As I use PuTTY in portable mode, then I'll check with the second option `plink.exe -certauthprompting -V` and `plink.exe -certauthpromptingoff -V`. Thank you for the tip. 👍 

Regards.
