### ISSUE TITLE
Question: Temporarily disable key

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#85]
Hi @NoMoreFood ,

I don't know if this can be done or not. But I prefer to ask:

- When we load a lot of keys (mainly using an script for example), from CAPI, PCKS and/or PuTTY keys; then we can have a list of ~10 keys. And in this scenario it will be interesting to "disable/enable" a key _without_ unloading it (aka deleting it).

It's this feasible?

**Comment by NoMoreFood** [comment]
Thanks for the idea, but not plan to implement this feature.  Recommend requesting it at the PuTTY level.
