### ISSUE TITLE
Question: Any method to order the keys/certs?

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#86]
An open question to all:

- In the Pageant Key List, the loaded keys/certs have a fixed order. The user can't move them. But the authentication is done in a specific order: from the upper/first to the lower/last.

Any idea to set an specific order?
Thank you.

**Comment by NoMoreFood** [comment]
I do appreciate the desire for this feature.  However, the upstream code uses archaic data structure called a 2-3-4 tree to store the keylist.  I see no functions to that would lend themselves to easily swapping elements or reordering.  Unlike PuTTY CAC, this capability would be useful across platforms so you might have luck submitting a feature request upstream.
