### ISSUE TITLE
Login with CAPI Cert not possible since 0.76.2

### ISSUE THREAD

**Issue by dheule** [NoMoreFood/putty-cac#87]
We are using Pagent with a certificate stored on yubikey.

With pagent from 0.76.1 it works perfectly, with pagent from 0.76.2 it doesn't work anymore.

On putty, we see the following lines (only since pagent 0.76.2):

```
Using username "cdist".
Authenticating with public key "CAPI:1b......(hash removed by me ...)                                                                                                        
" from agent
Server refused public-key signature despite accepting key!
Keyboard-interactive authentication prompts from server:
| Password:
```

With the same yubikey and pagent from 0.76.1 we see the following lines:

```
Using username "cdist".
Authenticating with public key "CAPI:1b......(hash removed by me ...)
" from agent
```
Then you are logged in ...

The key has the type following type: ecdsa-sha2-nistp384.

**Comment by NoMoreFood** [comment]
What application are you using with Pageant?  Just PuTTY?

**Comment by NoMoreFood** [comment]
Disregard previous issue.  I see the problem (specifically applies to ecdsa-sha2-nistp384).  Fix coming soon.

**Comment by dheule** [comment]
> Disregard previous issue. I see the problem (specifically applies to ecdsa-sha2-nistp384). Fix coming soon.

Thank you !

**Comment by NoMoreFood** [comment]
Can you try the updated binaries located at https://github.com/NoMoreFood/putty-cac/tree/master/binaries?

**Comment by dheule** [comment]
I have tested the new pageant, it works now
