### ISSUE TITLE
Pageant crashes when "cert/key auth promting" is enabled

### ISSUE THREAD

**Issue by donestefan** [NoMoreFood/putty-cac#88]
Steps to reproduce
1. start pageant and load putty key from disk
2. make sure  "cert/key auth promting" is enabled in pageant
3. open an ssh connection to a linux box 
-> pageant asks to allow signing operation -> say yes
-> ssh connection succeeds
4. close the ssh connection
5. open ssh connection again
-> pageant asks to allow signing operation -> say yes
=> pageant crashes before signing succeeds

Crashes do not happen with disabled "cert/key auth promting"
I'm using putty-cac 0.76-3 on win10 21H2

**Comment by NoMoreFood** [comment]
Just to confirm - this is specifically PuTTY keys?

**Comment by donestefan** [comment]
The key's "comment" in the second popup is the same as in the first.

**Comment by NoMoreFood** [comment]
Please see if the latest binaries posted here addresses the behavior: https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by donestefan** [comment]
I did a quick test using the new pageant stand-alone binary from [here](https://github.com/NoMoreFood/putty-cac/blob/master/binaries/x64/pageant.exe) (0.76u4) and it fixes my issue 👍  Thanks a lot!!!
