### ISSUE TITLE
Fetaure Request: add putty-cac to Windows Package Manager Repo

### ISSUE THREAD

**Issue by donestefan** [NoMoreFood/putty-cac#89]
Would you consider to add your software to Microsoft's "[Windows Package Manager Community Repo](https://github.com/microsoft/winget-pkgs)"? It would help to stay up-to-date with your latest releases. The package repo is basically a git based collection of software metadata, like published versions and download locations. Microsoft's new "[winget](https://github.com/microsoft/winget-cli)" command line installer/updater tool uses the metadata from this collection to help users update/install software. It is basically a windows replacement for linux' software repos (rpm/apt).

The authors of "nushell" wrote an example for software publishers on [how to automate the whole registration process](https://www.techwatching.dev/posts/wingetcreate#overview-of-the-created-workflow), using the registration helper [winget-create](https://github.com/microsoft/winget-create) and github actions.

**Comment by NoMoreFood** [comment]
Good idea. I submitted PR for it.

**Comment by NoMoreFood** [comment]
@donestefan They merged the change if you care to test it out.  The package is "nomorefood.putty-cac".   You may have to uninstall it first for the install to be successful.

**Comment by donestefan** [comment]
✅ detection of the already installed package works fine 

```
C:\>winget --version
v1.1.13405

C:\>winget list putty-cac
Name      ID                   Version  Quelle
-----------------------------------------------
PuTTY CAC NoMoreFood.PuTTY-CAC 0.76.0.4 winget
```
✅ uninstall works fine
```
C:\>winget uninstall NoMoreFood.PuTTY-CAC
Gefunden PuTTY CAC [NoMoreFood.PuTTY-CAC]
Paket-Deinstallation wird gestartet...
Erfolgreich deinstalliert
```
✅ install works fine
```
C:\>winget install NoMoreFood.PuTTY-CAC
Gefunden PuTTY CAC [NoMoreFood.PuTTY-CAC] Version 0.76.0.4
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://github.com/NoMoreFood/putty-cac/raw/0.76u4/binaries/puttycac-64bit-0.76u4-installer.msi
  ██████████████████████████████  2.96 MB / 2.96 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
```
Thanks a lot for your work!!! It's very much appreciated 👍
