### ISSUE TITLE
Question: Add CAPI thumbprint to Finger Print pull down

### ISSUE THREAD

**Issue by reggie-mcmurtrey** [NoMoreFood/putty-cac#90]
Would it be possible to add the CAPI thumbprint to the finger print pull down on the Pagent Key List window?  This way it would be easier to locate this thumbprint when adding it as a command line parameter.  If not through that method, any method to get this from the Pagent Key List window after a key is loaded would be very helpful.

**Comment by NoMoreFood** [comment]
I put this in as Ctrl+T (for thumbprint) in my local version that will be released when 0.77 is released.

**Comment by NoMoreFood** [comment]
If you want to confirm it's working for you, please try out these binaries:

https://github.com/NoMoreFood/putty-cac/tree/fido_dev_branch/binaries

**Comment by NoMoreFood** [comment]
Closing since this has been implemented in the pre-release.
