### ISSUE TITLE
CAPI dialog focus is inconsistent; could result in keyboard data being sent to wrong window

### ISSUE THREAD

**Issue by basgoossen** [NoMoreFood/putty-cac#91]
Whilst performing a CAC login on Putty, putty remains in the foreground when the Windows CAPI dialogs are shown (i.e. to enter pin or to touch device), this seems a windows issue, however: 

Keystrokes made with Putty in the foreground are later passed trough SSH after the login procedure is completed. This can lead to unwanted results and is even prone to security risks. Some more likely than others.

Likely: the pin of the capi device ends up beïng send to the server and possibly beïng stored in some logs or history.
Less likely: Bob could enter commands such as (rm *) before the login procedure and ask alice to complete the login, alice not knowing that by doing so se'd execute a malicious command on her behalf.

This information is soley a notice to inform the creators. All the work done by the Putty-CAC team is highly appreciated.

**Comment by NoMoreFood** [comment]
I'm working on some Window focus issues for the new FIDO code I'm working on so I'll revisit this.  Regardless of the application, it's always good to be extra careful what window has focus when entering sensitive information.  Renaming the title to be slightly less alarmist :-)

**Comment by NoMoreFood** [comment]
@basgoossen To help me along, can you provide for me the specifics of your environment?   What version / feature update of Windows?  What version of PuTTY is being used?  What is the make and model of your token?  Are you doing agent forwarding?  Is Pageant being used?  And anything else that you think could help.

**Comment by NoMoreFood** [comment]
@basgoossen If it was with Pageant, specifically, see if these binaries help: https://github.com/NoMoreFood/putty-cac/tree/fido_dev_branch/binaries

**Comment by NoMoreFood** [comment]
Closing due to non-responsiveness.

**Comment by basgoossen** [comment]
Hi NoMoreFood, at first my appologies for the non-responsiveness. For some reason i did not receive notifications about changes in this thread. Second thank you for your responses and work done. The situation improved when using both the new Putty.exe and peagent.exe. The focus is correctly shifted to the CAPI dialog.
So the risc of accidentaly typing pin code information is severely reduced.
What however remains is the possibility to inject (type in) malicious code in putty before the login is complete. The most logical thing to do is to clear the input buffer when the CAPI login is performed.

To give an example of what i mean with security risc here:
1. open putty and connect to the server
2. type in the username
3. as the pin code window appears change focus to putty again (this step is new now with the update)
4. type in a malicious command (to test use something as uptime) end press enter.
5. now "ask the owner of the capi device" to enter the pin code (because you'd need to do something on the server, of course this is suspicious, but it's easy to prevent)
6. when the pin code is entered the login is executed. Directly afterward the command entered in step 4 is executed

Point is that there are no visual queue's or warnings of what is going to happen when you log in. So it's best to clear the buffer once the login completes instead of processing it.

**Comment by NoMoreFood** [comment]
@basgoossen I understand what you're saying; I think is just a consequence of PuTTY (upstream) works and you'd end up seeing the problem with other authentication methods including standard public key authentication and password authentication if you mashed the keyboard at the right time before getting a shell prompt.  And, unfortunately, clearing that input buffer could negatively affect scenarios STDIN pipe is being proactively fed in by design (script or graphical automation scenarios).  I'll stew on it a little more and double-check to make sure the other authentication methods don't do anything special, but I suspect this one we may have to live with.

**Comment by basgoossen** [comment]
If other authentications in standard Putty also exhibit this problem, this should indeed not be on your list but on Putty's. Also there it can be considered acceptable. I just noticed the scenario and it felt like a possible risk. I am a frequent Putty user and never noticed this behaviour before with other authentication methods. However that does not mean it does not exist there, i just never noticed it.
Thanks again for your swift reply and for the effort and work you've put into this project!
