### ISSUE TITLE
PuTTY CAC 0.76 Update 4 missing certificate in SSH menu

### ISSUE THREAD

**Issue by Eivor78** [NoMoreFood/putty-cac#92]
This version is missing the certificate folder under Connection/SSH so that you can load your PIV or CAC card certificates. Please enable this for this release. It was available in older releases.

**Comment by NoMoreFood** [comment]
Can you please private a link to the download you are not seeing the Certificate menu in?

**Comment by NoMoreFood** [comment]
@Eivor78 Let me know which link doesn't seem to be looking for you.

**Comment by NoMoreFood** [comment]
Closing since I cannot reproduce.  Will reopen if @Eivor78 responds.
