### ISSUE TITLE
pterm.exe - Pseudo-console API error

### ISSUE THREAD

**Issue by usmcguy** [NoMoreFood/putty-cac#94]
When executing pterm.exe (both x86 and x64) on a Server 2016, receive the error:

Unable to open connection to
Pseudo-console API is not available on this Windows System

<img width="207" alt="image" src="https://user-images.githubusercontent.com/761929/172875283-1ec6bbf0-a6e6-4e81-8d4d-09089bdd47bb.png">

**Comment by NoMoreFood** [comment]
Yes, that is a known limitation.  Pseudo-consoles are only available on some operating systems.

**Comment by NoMoreFood** [comment]
Also, I should have noted that pterm.exe is brand new.  If you're looking for the command line version of PuTTY, it's plink.exe. 
 Since this is an upstream / OS limitation that I have no control over, closing this out.
