### ISSUE TITLE
The ECDSA_P384 certificate with yubikey is not selected.

### ISSUE THREAD

**Issue by assasinfil** [NoMoreFood/putty-cac#95]
It is not possible to select a certificate for authorization from the yubikey hardware token. When you select the ECDSA_P384 key, it does not appear in the list. But when choosing rsa, everything is fine. 
Putty cac v0.77 (latest release)
Windows 11
OpenSC 0.22.0

**Comment by NoMoreFood** [comment]
I cannot reproduce any issue with P384 selection, in general.  Can you list the steps in the interface you're going through and which step isn't working as desired?  Not clear whether you're using PuTTY or Pageant and whether it's PKCS / CAPI.  Also which Yubikey model?

**Comment by NoMoreFood** [comment]
Thank you for clarifying; I was trying with CAPI. I will try out OpenSC with PKCS this weekend.

**Comment by NoMoreFood** [comment]
@assasinfil Can you see if these binaries make any differences for you?  https://github.com/NoMoreFood/putty-cac/tree/master/binaries

Also, I've found the OpenSC PKCS libraries to be buggy / incomplete is some circumstances.  Might be worthwhile testing with the Yubikey PKCS Libary (aka YKCS) available here: https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-2.3.0-win64.msi

**Comment by NoMoreFood** [comment]
@assasinfil Any luck testing?  Also published this is a pre-release: https://github.com/NoMoreFood/putty-cac/releases/tag/0.77u1

**Comment by assasinfil** [comment]
I reinstalled the system. I'll try the binary files you suggested on the weekend.

**Comment by assasinfil** [comment]
> @assasinfil Any luck testing? Also published this is a pre-release: https://github.com/NoMoreFood/putty-cac/releases/tag/0.77u1

This version solves the problem, thank you!

**Comment by NoMoreFood** [comment]
Thank for you testing!
