### ISSUE TITLE
About page loses PuTTY-CAC reference after 0.77

### ISSUE THREAD

**Issue by rickatnight11** [NoMoreFood/putty-cac#96]
On 0.76 and earlier the About page had a useful reference to which build of PuTTY it is, which is easier to check than hunting for a specific feature:

![image](https://user-images.githubusercontent.com/76622/175305677-0a42e5ce-e24a-417a-9abc-68b50271e0c6.png)

....however that reference is lost in 0.77:

![image](https://user-images.githubusercontent.com/76622/175305783-0f3b060d-e456-4ea8-9b08-d76c0af35ca4.png)

...which is mostly indistinguishable from "vanilla" PuTTY:

![image](https://user-images.githubusercontent.com/76622/175305917-2862852c-f854-4447-bb03-f19e5f648ee1.png)

Would love to have this repo's URL added back to the About page for easier build identification.

**Comment by NoMoreFood** [comment]
Yeah, this is doable.

**Comment by NoMoreFood** [comment]
@rickatnight11 URL should be there now.

**Comment by rickatnight11** [comment]
That's great:

https://github.com/NoMoreFood/putty-cac/commit/b87c7aa9c90b42b2e4aecfe12084f9045deb7506#diff-ce5029cd82fba89c1252adb6124a18b1857815a002a481da794f6e111ec64f3eR3

Thanks so much!
