### ISSUE TITLE
configuration window freezes when I either attempt to "Set CAPI Cert" or "Set FIDO Key"

### ISSUE THREAD

**Issue by xeniphon** [NoMoreFood/putty-cac#98]
When I attempt to use either 0.77  or 0.77-1 with my PIV, I am never prompted to select the key.  After I poke the "Set CAPI Cert" the UI locks up.  No combination of alt-tab, drag-and-drop, or task-view makes it visible, and I can no longer move the putty window around on the screen.  0.76-4 still functions exactly as I expect.  The FIDO button does exactly the same thing as the CAPI button.

**Comment by NoMoreFood** [comment]
Okay thank you for the information.  Do you have any smartcard middleware installed like ActivClient and, if so, what version?
